/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Baize API
 * OpenAPI spec version: 1.0.0
 */
export type AgentCreateModelConfig = { [key: string]: unknown } | null;

/**
 * Request body for creating a new agent configuration.
 */
export interface AgentCreate {
  /**
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  system_prompt: string;
  tools: string[];
  description?: string | null;
  model_config?: AgentCreateModelConfig;
  auto_memory_recall?: boolean | null;
  shared_memory?: boolean | null;
  is_default?: boolean;
}

export type AgentResponseModelConfig = { [key: string]: unknown } | null;

/**
 * Agent configuration representation returned by the API.
 */
export interface AgentResponse {
  id: string;
  user_id: string;
  name: string;
  description: string | null;
  system_prompt: string;
  tools: string[] | null;
  model_config?: AgentResponseModelConfig;
  auto_memory_recall: boolean | null;
  shared_memory: boolean | null;
  is_default: boolean;
  created_at: string;
  updated_at: string;
}

export type AgentUpdateModelConfig = { [key: string]: unknown } | null;

/**
 * Request body for partially updating an agent configuration (PATCH semantics).
 */
export interface AgentUpdate {
  name?: string | null;
  system_prompt?: string | null;
  tools?: string[] | null;
  description?: string | null;
  model_config?: AgentUpdateModelConfig;
  auto_memory_recall?: boolean | null;
  shared_memory?: boolean | null;
  is_default?: boolean | null;
}

export type ChatMessageResponseToolCalls = { [key: string]: unknown } | null;

export type ChatMessageResponseTokenUsage = { [key: string]: unknown } | null;

export type MessageRole = (typeof MessageRole)[keyof typeof MessageRole];

export const MessageRole = {
  user: 'user',
  assistant: 'assistant',
  system: 'system',
  tool: 'tool'
} as const;

/**
 * Chat message representation returned by the API.
 */
export interface ChatMessageResponse {
  id: string;
  session_id: string;
  user_id: string;
  role: MessageRole;
  content: string;
  tool_calls: ChatMessageResponseToolCalls;
  tool_name: string | null;
  token_usage: ChatMessageResponseTokenUsage;
  created_at: string;
}

/**
 * Request body for the chat SSE endpoint.
 */
export interface ChatRequest {
  /** @minLength 1 */
  message: string;
}

/**
 * Request body for POST /api/v1/chat.
 */
export interface ChatStreamRequest {
  message: string;
  agent_id?: string | null;
  session_id?: string | null;
}

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

/**
 * Request body for the login endpoint.
 */
export interface LoginRequest {
  login: string;
  password: string;
}

/**
 * Paginated list of chat messages.
 */
export interface MessageListResponse {
  items: ChatMessageResponse[];
  total: number;
}

/**
 * Response for API key reset — contains new plaintext key.
 */
export interface ResetKeyResponse {
  api_key: string;
}

/**
 * Request body for creating a new session.
 */
export interface SessionCreate {
  title?: string | null;
}

export type SessionStatus = (typeof SessionStatus)[keyof typeof SessionStatus];

export const SessionStatus = {
  active: 'active',
  archived: 'archived'
} as const;

/**
 * Session representation returned by the API.
 */
export interface SessionResponse {
  id: string;
  user_id: string;
  agent_id: string;
  title: string | null;
  status: SessionStatus;
  auto_memory_recall: boolean | null;
  shared_memory: boolean | null;
  created_at: string;
  updated_at: string;
}

/**
 * Paginated list of sessions.
 */
export interface SessionListResponse {
  items: SessionResponse[];
  total: number;
}

/**
 * Request body for updating a session — only archiving is supported.
 */
export const SessionUpdateValue = {
  status: 'archived'
} as const;
export type SessionUpdate = typeof SessionUpdateValue;

export type TaskPriority = (typeof TaskPriority)[keyof typeof TaskPriority];

export const TaskPriority = {
  low: 'low',
  medium: 'medium',
  high: 'high'
} as const;

export type TaskSource = (typeof TaskSource)[keyof typeof TaskSource];

export const TaskSource = {
  manual: 'manual',
  agent: 'agent'
} as const;

/**
 * Request body for creating a new task.
 */
export interface TaskCreate {
  /**
   * @minLength 1
   * @maxLength 200
   */
  title: string;
  content?: string | null;
  priority?: TaskPriority;
  due_date?: string | null;
  tags?: string[] | null;
  source?: TaskSource;
}

export type TaskStatus = (typeof TaskStatus)[keyof typeof TaskStatus];

export const TaskStatus = {
  todo: 'todo',
  in_progress: 'in_progress',
  done: 'done'
} as const;

/**
 * Task representation returned by the API.
 */
export interface TaskResponse {
  id: string;
  user_id: string;
  title: string;
  content: string | null;
  priority: TaskPriority;
  status: TaskStatus;
  due_date: string | null;
  source: TaskSource;
  tags: unknown[] | null;
  related_memory_id: string | null;
  completed_at: string | null;
  created_at: string;
  updated_at: string;
}

/**
 * Paginated list of tasks.
 */
export interface TaskListResponse {
  items: TaskResponse[];
  total: number;
}

/**
 * Request body for partially updating a task (PATCH).
 */
export interface TaskUpdate {
  title?: string | null;
  content?: string | null;
  priority?: TaskPriority | null;
  status?: TaskStatus | null;
  due_date?: string | null;
  tags?: string[] | null;
}

/**
 * Request body for the LLM connectivity test endpoint.
 */
export interface TestRequest {
  provider: string;
  model: string;
}

/**
 * Response body for the LLM connectivity test endpoint.
 */
export interface TestResponse {
  success: boolean;
  latency_ms?: number | null;
  error?: string | null;
}

/**
 * Token response returned by login and refresh.
 */
export interface TokenResponse {
  access_token: string;
  token_type: string;
  expires_in: number;
}

export type UserCreateRequestPreferences = { [key: string]: unknown } | null;

/**
 * Request body for creating a new user.
 */
export interface UserCreateRequest {
  email: string;
  name: string;
  password: string;
  role?: string;
  avatar?: string | null;
  preferences?: UserCreateRequestPreferences;
}

export type UserCreateResponsePreferences = { [key: string]: unknown } | null;

/**
 * Response for user creation — includes one-time plaintext api_key.
 */
export interface UserCreateResponse {
  id: string;
  email: string;
  name: string;
  role: string;
  avatar: string | null;
  preferences: UserCreateResponsePreferences;
  is_active: boolean;
  created_at: string;
  updated_at: string;
  api_key: string;
}

export type UserResponsePreferences = { [key: string]: unknown } | null;

/**
 * Public user representation — excludes password and api_key_hash.
 */
export interface UserResponse {
  id: string;
  email: string;
  name: string;
  role: string;
  avatar: string | null;
  preferences: UserResponsePreferences;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

/**
 * Paginated list of users.
 */
export interface UserListResponse {
  items: UserResponse[];
  total: number;
}

export type UserUpdateRequestPreferences = { [key: string]: unknown } | null;

/**
 * Request body for updating the current user.
 */
export interface UserUpdateRequest {
  name?: string | null;
  avatar?: string | null;
  preferences?: UserUpdateRequestPreferences;
}

export type LogoutApiV1AuthLogoutPost200 = { [key: string]: string };

export type ListUsersApiV1UsersGetParams = {
  skip?: number;
  limit?: number;
};

export type ListProvidersApiV1LlmProvidersGet200Item = {
  [key: string]: unknown;
};

export type ListSessionsApiV1AgentsAgentIdSessionsGetParams = {
  status?: SessionStatus | null;
  limit?: number;
  offset?: number;
};

export type ListMessagesApiV1SessionsSessionIdMessagesGetParams = {
  limit?: number;
  offset?: number;
};

export type ListTasksApiV1TasksGetParams = {
  status?: TaskStatus | null;
  priority?: TaskPriority | null;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * @minimum 0
   */
  offset?: number;
};

export type HealthHealthGet200 = { [key: string]: string };
