/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Baize API
 * OpenAPI spec version: 1.0.0
 */
export type AgentCreateModelConfig = { [key: string]: unknown } | null;

/**
 * 分层 prompt 配置。所有层都可选，按存在的层依次组装。
 */
export interface AgentPrompts {
  soul?: string | null;
  behavior?: string | null;
}

/**
 * 工具配置结构。
 */
export interface ToolsConfig {
  builtin?: string[];
  mcp_servers?: string[];
  skills?: string[];
}

/**
 * 记忆策略配置。
 */
export interface MemoryConfig {
  auto_recall?: boolean;
  shared?: boolean;
  top_k?: number;
}

/**
 * 执行护栏配置。
 */
export interface GuardrailsConfig {
  max_tool_calls?: number;
  timeout_seconds?: number;
  max_tokens_per_turn?: number | null;
}

/**
 * Request body for creating a new agent configuration.
 */
export interface AgentCreate {
  /**
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  description?: string | null;
  agent_type?: string;
  prompts?: AgentPrompts;
  model_config?: AgentCreateModelConfig;
  tools?: ToolsConfig;
  sub_agents?: string[] | null;
  memory_config?: MemoryConfig;
  guardrails?: GuardrailsConfig;
  set_as_default?: boolean;
}

export type AgentResponseModelConfig = { [key: string]: unknown } | null;

/**
 * Agent configuration representation returned by the API.
 */
export interface AgentResponse {
  id: string;
  user_id: string;
  name: string;
  description: string | null;
  agent_type: string;
  prompts: AgentPrompts | null;
  model_config?: AgentResponseModelConfig;
  tools: ToolsConfig | null;
  sub_agents: string[] | null;
  memory_config: MemoryConfig | null;
  guardrails: GuardrailsConfig | null;
  is_enabled: boolean;
  created_at: string;
  updated_at: string;
}

export type AgentUpdateModelConfig = { [key: string]: unknown } | null;

/**
 * Request body for partially updating an agent configuration (PATCH semantics).
 */
export interface AgentUpdate {
  name?: string | null;
  description?: string | null;
  agent_type?: string | null;
  prompts?: AgentPrompts | null;
  model_config?: AgentUpdateModelConfig;
  tools?: ToolsConfig | null;
  sub_agents?: string[] | null;
  memory_config?: MemoryConfig | null;
  guardrails?: GuardrailsConfig | null;
  set_as_default?: boolean | null;
  is_enabled?: boolean | null;
}

export interface OpenAIMessage {
  role: string;
  content: string;
}

export interface ChatCompletionRequest {
  model: string;
  messages: OpenAIMessage[];
  stream?: boolean;
  temperature?: number | null;
  max_tokens?: number | null;
  user?: string | null;
  agent_id?: string | null;
  session_id?: string | null;
  [key: string]: unknown;
}

export type ChatMessageResponseToolCalls = { [key: string]: unknown } | null;

export type ChatMessageResponseTokenUsage = { [key: string]: unknown } | null;

export type MessageRole = (typeof MessageRole)[keyof typeof MessageRole];

export const MessageRole = {
  user: 'user',
  assistant: 'assistant',
  system: 'system',
  tool: 'tool'
} as const;

/**
 * Chat message representation returned by the API.
 */
export interface ChatMessageResponse {
  id: string;
  session_id: string;
  user_id: string;
  role: MessageRole;
  content: string;
  tool_calls: ChatMessageResponseToolCalls;
  tool_name: string | null;
  token_usage: ChatMessageResponseTokenUsage;
  created_at: string;
}

/**
 * Request body for POST /api/v1/chat.
 */
export interface ChatStreamRequest {
  message: string;
  agent_id?: string | null;
  session_id?: string | null;
}

/**
 * Empty body — just creates a new conversation.
 */
export interface ConversationCreateRequest {
  [key: string]: unknown;
}

export interface ConversationObject {
  id: string;
  object?: string;
  created_at?: number;
}

export type FieldDescriptorType =
  (typeof FieldDescriptorType)[keyof typeof FieldDescriptorType];

export const FieldDescriptorType = {
  text: 'text',
  textarea: 'textarea',
  int: 'int',
  bool: 'bool',
  select: 'select',
  multi_select: 'multi_select',
  date: 'date'
} as const;

export type FieldDescriptorConstraints = { [key: string]: unknown } | null;

/**
 * A single selectable option for select / multi_select fields.
 */
export interface FieldOption {
  value: string;
  label: string;
  disabled?: boolean;
}

/**
 * Describes one form field.

Attributes:
    key: Dot-notation path (e.g. ``guardrails.max_tool_calls``).
    label: Display label (Chinese).
    description: Help text shown under the field.
    type: Determines which frontend widget to render.
    required: Whether the field is mandatory.
    default: Default value for new records.
    constraints: Type-specific validation rules:
        text/textarea: ``{"min_length": int, "max_length": int}``
        int: ``{"min": int, "max": int}``
        multi_select: ``{"max_items": int}``
    options: Pre-resolved selectable options (always populated for select types).
    options_ref: Semantic hint that options are dynamic (e.g. ``"llm_models_chat"``).
        Frontend may show a refresh button for such fields.
 */
export interface FieldDescriptor {
  key: string;
  label: string;
  description?: string | null;
  type: FieldDescriptorType;
  required?: boolean;
  default?: unknown;
  constraints?: FieldDescriptorConstraints;
  options?: FieldOption[] | null;
  options_ref?: string | null;
}

/**
 * Visual grouping of fields for form layout.
 */
export interface FieldGroup {
  key: string;
  label: string;
  sort?: number;
  fields: FieldDescriptor[];
}

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

/**
 * Request body for the login endpoint.
 */
export interface LoginRequest {
  login: string;
  password: string;
}

/**
 * Paginated list of chat messages.
 */
export interface MessageListResponse {
  items: ChatMessageResponse[];
  total: number;
}

export interface ModelObject {
  id: string;
  object?: string;
  created?: number;
  owned_by?: string;
}

export interface ModelListResponse {
  object?: string;
  data: ModelObject[];
}

/**
 * Reasoning/thinking configuration.
 */
export interface ReasoningConfig {
  effort?: string;
}

/**
 * Response for API key reset — contains new plaintext key.
 */
export interface ResetKeyResponse {
  api_key: string;
}

/**
 * Top-level response for ``GET /api/v1/metadata/{resource}``.
 */
export interface ResourceMetadata {
  resource: string;
  groups: FieldGroup[];
}

export type ResponsesRequestInput =
  | string
  | OpenAIMessage[]
  | { [key: string]: unknown }[];

export interface ResponsesRequest {
  model: string;
  input: ResponsesRequestInput;
  instructions?: string | null;
  conversation?: string | null;
  previous_response_id?: string | null;
  stream?: boolean;
  store?: boolean;
  temperature?: number | null;
  max_output_tokens?: number | null;
  reasoning?: ReasoningConfig | null;
  agent_id?: string | null;
  [key: string]: unknown;
}

/**
 * Request body for creating a new session.
 */
export interface SessionCreate {
  title?: string | null;
}

export type SessionStatus = (typeof SessionStatus)[keyof typeof SessionStatus];

export const SessionStatus = {
  active: 'active',
  archived: 'archived',
  deleted: 'deleted'
} as const;

/**
 * Session representation returned by the API.
 */
export interface SessionResponse {
  id: string;
  user_id: string;
  agent_id: string;
  title: string | null;
  status: SessionStatus;
  created_at: string;
  updated_at: string;
}

/**
 * Paginated list of sessions.
 */
export interface SessionListResponse {
  items: SessionResponse[];
  total: number;
}

/**
 * Request body for updating a session (title and/or status).
 */
export interface SessionUpdate {
  title?: string | null;
  status?: 'active' | 'archived' | null;
}

export type TaskPriority = (typeof TaskPriority)[keyof typeof TaskPriority];

export const TaskPriority = {
  low: 'low',
  medium: 'medium',
  high: 'high'
} as const;

export type TaskSource = (typeof TaskSource)[keyof typeof TaskSource];

export const TaskSource = {
  manual: 'manual',
  agent: 'agent'
} as const;

/**
 * Request body for creating a new task.
 */
export interface TaskCreate {
  /**
   * @minLength 1
   * @maxLength 200
   */
  title: string;
  content?: string | null;
  priority?: TaskPriority;
  due_date?: string | null;
  tags?: string[] | null;
  source?: TaskSource;
}

export type TaskStatus = (typeof TaskStatus)[keyof typeof TaskStatus];

export const TaskStatus = {
  todo: 'todo',
  in_progress: 'in_progress',
  done: 'done'
} as const;

/**
 * Task representation returned by the API.
 */
export interface TaskResponse {
  id: string;
  user_id: string;
  title: string;
  content: string | null;
  priority: TaskPriority;
  status: TaskStatus;
  due_date: string | null;
  source: TaskSource;
  tags: unknown[] | null;
  related_memory_id: string | null;
  completed_at: string | null;
  created_at: string;
  updated_at: string;
}

/**
 * Paginated list of tasks.
 */
export interface TaskListResponse {
  items: TaskResponse[];
  total: number;
}

/**
 * Request body for partially updating a task (PATCH).
 */
export interface TaskUpdate {
  title?: string | null;
  content?: string | null;
  priority?: TaskPriority | null;
  status?: TaskStatus | null;
  due_date?: string | null;
  tags?: string[] | null;
}

/**
 * Request body for the LLM connectivity test endpoint.
 */
export interface TestRequest {
  provider: string;
  model: string;
}

/**
 * Response body for the LLM connectivity test endpoint.
 */
export interface TestResponse {
  success: boolean;
  latency_ms?: number | null;
  error?: string | null;
}

/**
 * Token response returned by login and refresh.
 */
export interface TokenResponse {
  access_token: string;
  token_type: string;
  expires_in: number;
}

export type UserCreateRequestPreferences = { [key: string]: unknown } | null;

/**
 * Request body for creating a new user.
 */
export interface UserCreateRequest {
  email: string;
  name: string;
  password: string;
  role?: string;
  avatar?: string | null;
  preferences?: UserCreateRequestPreferences;
}

export type UserCreateResponsePreferences = { [key: string]: unknown } | null;

/**
 * Response for user creation — includes one-time plaintext api_key.
 */
export interface UserCreateResponse {
  id: string;
  email: string;
  name: string;
  role: string;
  avatar: string | null;
  preferences: UserCreateResponsePreferences;
  is_active: boolean;
  created_at: string;
  updated_at: string;
  api_key: string;
}

export type UserResponsePreferences = { [key: string]: unknown } | null;

/**
 * Public user representation — excludes password and api_key_hash.
 */
export interface UserResponse {
  id: string;
  email: string;
  name: string;
  role: string;
  avatar: string | null;
  preferences: UserResponsePreferences;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

/**
 * Paginated list of users.
 */
export interface UserListResponse {
  items: UserResponse[];
  total: number;
}

export type UserUpdateRequestPreferences = { [key: string]: unknown } | null;

/**
 * Request body for updating the current user.
 */
export interface UserUpdateRequest {
  name?: string | null;
  avatar?: string | null;
  preferences?: UserUpdateRequestPreferences;
}

export type LogoutApiV1AuthLogoutPost200 = { [key: string]: string };

export type ListUsersApiV1UsersGetParams = {
  skip?: number;
  limit?: number;
};

export type ListProvidersApiV1LlmProvidersGet200Item = {
  [key: string]: unknown;
};

export type ListSessionsApiV1AgentsAgentIdSessionsGetParams = {
  status?: SessionStatus | null;
  limit?: number;
  offset?: number;
};

export type ListMessagesApiV1SessionsSessionIdMessagesGetParams = {
  limit?: number;
  offset?: number;
  before?: string | null;
};

export type ListTasksApiV1TasksGetParams = {
  status?: TaskStatus | null;
  priority?: TaskPriority | null;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * @minimum 0
   */
  offset?: number;
};

export type ListResourcesApiV1MetadataGet200 = { [key: string]: unknown };

export type HealthHealthGet200 = { [key: string]: string };
