/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Baize API
 * OpenAPI spec version: 1.0.0
 */
import type {
  HTTPValidationError,
  ListResourcesApiV1MetadataGet200,
  ResourceMetadata
} from '../baizeAPI.schemas';

import { customFetch } from '.././custom-fetch';

/**
 * Return the list of resources that have metadata definitions.
 * @summary List Resources
 */
export type listResourcesApiV1MetadataGetResponse200 = {
  data: ListResourcesApiV1MetadataGet200;
  status: 200;
};

export type listResourcesApiV1MetadataGetResponseSuccess =
  listResourcesApiV1MetadataGetResponse200 & {
    headers: Headers;
  };
export type listResourcesApiV1MetadataGetResponse =
  listResourcesApiV1MetadataGetResponseSuccess;

export const getListResourcesApiV1MetadataGetUrl = () => {
  return `/api/v1/metadata`;
};

export const listResourcesApiV1MetadataGet = async (
  options?: RequestInit
): Promise<listResourcesApiV1MetadataGetResponse> => {
  return customFetch<listResourcesApiV1MetadataGetResponse>(
    getListResourcesApiV1MetadataGetUrl(),
    {
      ...options,
      method: 'GET'
    }
  );
};

/**
 * Return field schema and options for the given resource.
 * @summary Get Resource Metadata
 */
export type getResourceMetadataApiV1MetadataResourceGetResponse200 = {
  data: ResourceMetadata;
  status: 200;
};

export type getResourceMetadataApiV1MetadataResourceGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getResourceMetadataApiV1MetadataResourceGetResponseSuccess =
  getResourceMetadataApiV1MetadataResourceGetResponse200 & {
    headers: Headers;
  };
export type getResourceMetadataApiV1MetadataResourceGetResponseError =
  getResourceMetadataApiV1MetadataResourceGetResponse422 & {
    headers: Headers;
  };

export type getResourceMetadataApiV1MetadataResourceGetResponse =
  | getResourceMetadataApiV1MetadataResourceGetResponseSuccess
  | getResourceMetadataApiV1MetadataResourceGetResponseError;

export const getGetResourceMetadataApiV1MetadataResourceGetUrl = (
  resource: string
) => {
  return `/api/v1/metadata/${resource}`;
};

export const getResourceMetadataApiV1MetadataResourceGet = async (
  resource: string,
  options?: RequestInit
): Promise<getResourceMetadataApiV1MetadataResourceGetResponse> => {
  return customFetch<getResourceMetadataApiV1MetadataResourceGetResponse>(
    getGetResourceMetadataApiV1MetadataResourceGetUrl(resource),
    {
      ...options,
      method: 'GET'
    }
  );
};
