/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * DiTing API
 * 代码知识图谱分析系统 — 多语言、Neo4j、FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { customFetch } from '.././custom-fetch';

/**
 * @summary Health
 */
export type healthHealthGetResponse200 = {
  data: unknown;
  status: 200;
};

export type healthHealthGetResponseSuccess = healthHealthGetResponse200 & {
  headers: Headers;
};
export type healthHealthGetResponse = healthHealthGetResponseSuccess;

export const getHealthHealthGetUrl = () => {
  return `/health`;
};

export const healthHealthGet = async (
  options?: RequestInit
): Promise<healthHealthGetResponse> => {
  return customFetch<healthHealthGetResponse>(getHealthHealthGetUrl(), {
    ...options,
    method: 'GET'
  });
};
