/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * DiTing API
 * 代码知识图谱分析系统 — 多语言、Neo4j、FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type {
  CloneRequest,
  EnhanceRequest,
  HTTPValidationError,
  ListProjectsApiProjectsGetParams,
  PageProject,
  Project,
  ProjectCreate,
  ProjectUpdate,
  ScanRequest
} from '../diTingAPI.schemas';

import { customFetch } from '.././custom-fetch';

/**
 * @summary List Projects
 */
export type listProjectsApiProjectsGetResponse200 = {
  data: PageProject;
  status: 200;
};

export type listProjectsApiProjectsGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type listProjectsApiProjectsGetResponseSuccess =
  listProjectsApiProjectsGetResponse200 & {
    headers: Headers;
  };
export type listProjectsApiProjectsGetResponseError =
  listProjectsApiProjectsGetResponse422 & {
    headers: Headers;
  };

export type listProjectsApiProjectsGetResponse =
  | listProjectsApiProjectsGetResponseSuccess
  | listProjectsApiProjectsGetResponseError;

export const getListProjectsApiProjectsGetUrl = (
  params?: ListProjectsApiProjectsGetParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/projects?${stringifiedParams}`
    : `/api/projects`;
};

export const listProjectsApiProjectsGet = async (
  params?: ListProjectsApiProjectsGetParams,
  options?: RequestInit
): Promise<listProjectsApiProjectsGetResponse> => {
  return customFetch<listProjectsApiProjectsGetResponse>(
    getListProjectsApiProjectsGetUrl(params),
    {
      ...options,
      method: 'GET'
    }
  );
};

/**
 * @summary Create Project
 */
export type createProjectApiProjectsPostResponse201 = {
  data: Project;
  status: 201;
};

export type createProjectApiProjectsPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createProjectApiProjectsPostResponseSuccess =
  createProjectApiProjectsPostResponse201 & {
    headers: Headers;
  };
export type createProjectApiProjectsPostResponseError =
  createProjectApiProjectsPostResponse422 & {
    headers: Headers;
  };

export type createProjectApiProjectsPostResponse =
  | createProjectApiProjectsPostResponseSuccess
  | createProjectApiProjectsPostResponseError;

export const getCreateProjectApiProjectsPostUrl = () => {
  return `/api/projects`;
};

export const createProjectApiProjectsPost = async (
  projectCreate: ProjectCreate,
  options?: RequestInit
): Promise<createProjectApiProjectsPostResponse> => {
  return customFetch<createProjectApiProjectsPostResponse>(
    getCreateProjectApiProjectsPostUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(projectCreate)
    }
  );
};

/**
 * @summary Get Project
 */
export type getProjectApiProjectsProjectIdGetResponse200 = {
  data: Project;
  status: 200;
};

export type getProjectApiProjectsProjectIdGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getProjectApiProjectsProjectIdGetResponseSuccess =
  getProjectApiProjectsProjectIdGetResponse200 & {
    headers: Headers;
  };
export type getProjectApiProjectsProjectIdGetResponseError =
  getProjectApiProjectsProjectIdGetResponse422 & {
    headers: Headers;
  };

export type getProjectApiProjectsProjectIdGetResponse =
  | getProjectApiProjectsProjectIdGetResponseSuccess
  | getProjectApiProjectsProjectIdGetResponseError;

export const getGetProjectApiProjectsProjectIdGetUrl = (projectId: string) => {
  return `/api/projects/${projectId}`;
};

export const getProjectApiProjectsProjectIdGet = async (
  projectId: string,
  options?: RequestInit
): Promise<getProjectApiProjectsProjectIdGetResponse> => {
  return customFetch<getProjectApiProjectsProjectIdGetResponse>(
    getGetProjectApiProjectsProjectIdGetUrl(projectId),
    {
      ...options,
      method: 'GET'
    }
  );
};

/**
 * @summary Update Project
 */
export type updateProjectApiProjectsProjectIdPutResponse200 = {
  data: Project;
  status: 200;
};

export type updateProjectApiProjectsProjectIdPutResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type updateProjectApiProjectsProjectIdPutResponseSuccess =
  updateProjectApiProjectsProjectIdPutResponse200 & {
    headers: Headers;
  };
export type updateProjectApiProjectsProjectIdPutResponseError =
  updateProjectApiProjectsProjectIdPutResponse422 & {
    headers: Headers;
  };

export type updateProjectApiProjectsProjectIdPutResponse =
  | updateProjectApiProjectsProjectIdPutResponseSuccess
  | updateProjectApiProjectsProjectIdPutResponseError;

export const getUpdateProjectApiProjectsProjectIdPutUrl = (
  projectId: string
) => {
  return `/api/projects/${projectId}`;
};

export const updateProjectApiProjectsProjectIdPut = async (
  projectId: string,
  projectUpdate: ProjectUpdate,
  options?: RequestInit
): Promise<updateProjectApiProjectsProjectIdPutResponse> => {
  return customFetch<updateProjectApiProjectsProjectIdPutResponse>(
    getUpdateProjectApiProjectsProjectIdPutUrl(projectId),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(projectUpdate)
    }
  );
};

/**
 * @summary Delete Project
 */
export type deleteProjectApiProjectsProjectIdDeleteResponse204 = {
  data: void;
  status: 204;
};

export type deleteProjectApiProjectsProjectIdDeleteResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type deleteProjectApiProjectsProjectIdDeleteResponseSuccess =
  deleteProjectApiProjectsProjectIdDeleteResponse204 & {
    headers: Headers;
  };
export type deleteProjectApiProjectsProjectIdDeleteResponseError =
  deleteProjectApiProjectsProjectIdDeleteResponse422 & {
    headers: Headers;
  };

export type deleteProjectApiProjectsProjectIdDeleteResponse =
  | deleteProjectApiProjectsProjectIdDeleteResponseSuccess
  | deleteProjectApiProjectsProjectIdDeleteResponseError;

export const getDeleteProjectApiProjectsProjectIdDeleteUrl = (
  projectId: string
) => {
  return `/api/projects/${projectId}`;
};

export const deleteProjectApiProjectsProjectIdDelete = async (
  projectId: string,
  options?: RequestInit
): Promise<deleteProjectApiProjectsProjectIdDeleteResponse> => {
  return customFetch<deleteProjectApiProjectsProjectIdDeleteResponse>(
    getDeleteProjectApiProjectsProjectIdDeleteUrl(projectId),
    {
      ...options,
      method: 'DELETE'
    }
  );
};

/**
 * 克隆项目仓库到本地工作区（根据项目的 repo_url / branch）
 * @summary Clone Project
 */
export type cloneProjectApiProjectsProjectIdClonePostResponse200 = {
  data: unknown;
  status: 200;
};

export type cloneProjectApiProjectsProjectIdClonePostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type cloneProjectApiProjectsProjectIdClonePostResponseSuccess =
  cloneProjectApiProjectsProjectIdClonePostResponse200 & {
    headers: Headers;
  };
export type cloneProjectApiProjectsProjectIdClonePostResponseError =
  cloneProjectApiProjectsProjectIdClonePostResponse422 & {
    headers: Headers;
  };

export type cloneProjectApiProjectsProjectIdClonePostResponse =
  | cloneProjectApiProjectsProjectIdClonePostResponseSuccess
  | cloneProjectApiProjectsProjectIdClonePostResponseError;

export const getCloneProjectApiProjectsProjectIdClonePostUrl = (
  projectId: string
) => {
  return `/api/projects/${projectId}/clone`;
};

export const cloneProjectApiProjectsProjectIdClonePost = async (
  projectId: string,
  cloneRequest: CloneRequest,
  options?: RequestInit
): Promise<cloneProjectApiProjectsProjectIdClonePostResponse> => {
  return customFetch<cloneProjectApiProjectsProjectIdClonePostResponse>(
    getCloneProjectApiProjectsProjectIdClonePostUrl(projectId),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(cloneRequest)
    }
  );
};

/**
 * @summary Scan Project
 */
export type scanProjectApiProjectsProjectIdScanPostResponse200 = {
  data: unknown;
  status: 200;
};

export type scanProjectApiProjectsProjectIdScanPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type scanProjectApiProjectsProjectIdScanPostResponseSuccess =
  scanProjectApiProjectsProjectIdScanPostResponse200 & {
    headers: Headers;
  };
export type scanProjectApiProjectsProjectIdScanPostResponseError =
  scanProjectApiProjectsProjectIdScanPostResponse422 & {
    headers: Headers;
  };

export type scanProjectApiProjectsProjectIdScanPostResponse =
  | scanProjectApiProjectsProjectIdScanPostResponseSuccess
  | scanProjectApiProjectsProjectIdScanPostResponseError;

export const getScanProjectApiProjectsProjectIdScanPostUrl = (
  projectId: string
) => {
  return `/api/projects/${projectId}/scan`;
};

export const scanProjectApiProjectsProjectIdScanPost = async (
  projectId: string,
  scanRequest: ScanRequest,
  options?: RequestInit
): Promise<scanProjectApiProjectsProjectIdScanPostResponse> => {
  return customFetch<scanProjectApiProjectsProjectIdScanPostResponse>(
    getScanProjectApiProjectsProjectIdScanPostUrl(projectId),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(scanRequest)
    }
  );
};

/**
 * @summary Enhance Project
 */
export type enhanceProjectApiProjectsProjectIdEnhancePostResponse200 = {
  data: unknown;
  status: 200;
};

export type enhanceProjectApiProjectsProjectIdEnhancePostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type enhanceProjectApiProjectsProjectIdEnhancePostResponseSuccess =
  enhanceProjectApiProjectsProjectIdEnhancePostResponse200 & {
    headers: Headers;
  };
export type enhanceProjectApiProjectsProjectIdEnhancePostResponseError =
  enhanceProjectApiProjectsProjectIdEnhancePostResponse422 & {
    headers: Headers;
  };

export type enhanceProjectApiProjectsProjectIdEnhancePostResponse =
  | enhanceProjectApiProjectsProjectIdEnhancePostResponseSuccess
  | enhanceProjectApiProjectsProjectIdEnhancePostResponseError;

export const getEnhanceProjectApiProjectsProjectIdEnhancePostUrl = (
  projectId: string
) => {
  return `/api/projects/${projectId}/enhance`;
};

export const enhanceProjectApiProjectsProjectIdEnhancePost = async (
  projectId: string,
  enhanceRequest: EnhanceRequest,
  options?: RequestInit
): Promise<enhanceProjectApiProjectsProjectIdEnhancePostResponse> => {
  return customFetch<enhanceProjectApiProjectsProjectIdEnhancePostResponse>(
    getEnhanceProjectApiProjectsProjectIdEnhancePostUrl(projectId),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(enhanceRequest)
    }
  );
};
