/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Baize API
 * OpenAPI spec version: 1.0.0
 */
import type {
  ChatStreamRequest,
  HTTPValidationError
} from '../baizeAPI.schemas';

import { customFetch } from '.././custom-fetch';

/**
 * Stream a chat turn as server-sent events (SSE).

Resolves the agent (default if not specified), validates session ownership,
auto-creates a session if needed, then delegates to AgentService.chat().

Returns:
    EventSourceResponse with Content-Type: text/event-stream.

Raises:
    HTTPException: 400 if message is empty, 403 if session not owned,
        404 if default agent not found.
 * @summary Chat Stream
 */
export type chatStreamApiV1ChatPostResponse200 = {
  data: unknown;
  status: 200;
};

export type chatStreamApiV1ChatPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type chatStreamApiV1ChatPostResponseSuccess =
  chatStreamApiV1ChatPostResponse200 & {
    headers: Headers;
  };
export type chatStreamApiV1ChatPostResponseError =
  chatStreamApiV1ChatPostResponse422 & {
    headers: Headers;
  };

export type chatStreamApiV1ChatPostResponse =
  | chatStreamApiV1ChatPostResponseSuccess
  | chatStreamApiV1ChatPostResponseError;

export const getChatStreamApiV1ChatPostUrl = () => {
  return `/api/v1/chat`;
};

export const chatStreamApiV1ChatPost = async (
  chatStreamRequest: ChatStreamRequest,
  options?: RequestInit
): Promise<chatStreamApiV1ChatPostResponse> => {
  return customFetch<chatStreamApiV1ChatPostResponse>(
    getChatStreamApiV1ChatPostUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(chatStreamRequest)
    }
  );
};

/**
 * Return a complete chat turn as a single JSON response.

Collects all events from AgentService.chat() and assembles the full
response before returning.

Returns:
    ApiResponse wrapping ChatSyncResponse with code=0.

Raises:
    HTTPException: 400 if message is empty, 403 if session not owned,
        404 if default agent not found, 500 on agent error.
 * @summary Chat Sync
 */
export type chatSyncApiV1ChatSyncPostResponse200 = {
  data: unknown;
  status: 200;
};

export type chatSyncApiV1ChatSyncPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type chatSyncApiV1ChatSyncPostResponseSuccess =
  chatSyncApiV1ChatSyncPostResponse200 & {
    headers: Headers;
  };
export type chatSyncApiV1ChatSyncPostResponseError =
  chatSyncApiV1ChatSyncPostResponse422 & {
    headers: Headers;
  };

export type chatSyncApiV1ChatSyncPostResponse =
  | chatSyncApiV1ChatSyncPostResponseSuccess
  | chatSyncApiV1ChatSyncPostResponseError;

export const getChatSyncApiV1ChatSyncPostUrl = () => {
  return `/api/v1/chat/sync`;
};

export const chatSyncApiV1ChatSyncPost = async (
  chatStreamRequest: ChatStreamRequest,
  options?: RequestInit
): Promise<chatSyncApiV1ChatSyncPostResponse> => {
  return customFetch<chatSyncApiV1ChatSyncPostResponse>(
    getChatSyncApiV1ChatSyncPostUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(chatStreamRequest)
    }
  );
};
