/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * DiTing API
 * 代码知识图谱分析系统 — 多语言、Neo4j、FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type {
  AskRequest,
  HTTPValidationError,
  RunCypherApiCypherPostBody
} from '../diTingAPI.schemas';

import { customFetch } from '.././custom-fetch';

/**
 * 查看语言 schema 声明
 * @summary Get Schema
 */
export type getSchemaApiSchemaLanguageGetResponse200 = {
  data: unknown;
  status: 200;
};

export type getSchemaApiSchemaLanguageGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getSchemaApiSchemaLanguageGetResponseSuccess =
  getSchemaApiSchemaLanguageGetResponse200 & {
    headers: Headers;
  };
export type getSchemaApiSchemaLanguageGetResponseError =
  getSchemaApiSchemaLanguageGetResponse422 & {
    headers: Headers;
  };

export type getSchemaApiSchemaLanguageGetResponse =
  | getSchemaApiSchemaLanguageGetResponseSuccess
  | getSchemaApiSchemaLanguageGetResponseError;

export const getGetSchemaApiSchemaLanguageGetUrl = (language: string) => {
  return `/api/schema/${language}`;
};

export const getSchemaApiSchemaLanguageGet = async (
  language: string,
  options?: RequestInit
): Promise<getSchemaApiSchemaLanguageGetResponse> => {
  return customFetch<getSchemaApiSchemaLanguageGetResponse>(
    getGetSchemaApiSchemaLanguageGetUrl(language),
    {
      ...options,
      method: 'GET'
    }
  );
};

/**
 * 列出所有已注册的语言插件
 * @summary List Languages
 */
export type listLanguagesApiLanguagesGetResponse200 = {
  data: unknown;
  status: 200;
};

export type listLanguagesApiLanguagesGetResponseSuccess =
  listLanguagesApiLanguagesGetResponse200 & {
    headers: Headers;
  };
export type listLanguagesApiLanguagesGetResponse =
  listLanguagesApiLanguagesGetResponseSuccess;

export const getListLanguagesApiLanguagesGetUrl = () => {
  return `/api/languages`;
};

export const listLanguagesApiLanguagesGet = async (
  options?: RequestInit
): Promise<listLanguagesApiLanguagesGetResponse> => {
  return customFetch<listLanguagesApiLanguagesGetResponse>(
    getListLanguagesApiLanguagesGetUrl(),
    {
      ...options,
      method: 'GET'
    }
  );
};

/**
 * 执行原始 Cypher 语句（用于调试）
 * @summary Run Cypher
 */
export type runCypherApiCypherPostResponse200 = {
  data: unknown;
  status: 200;
};

export type runCypherApiCypherPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type runCypherApiCypherPostResponseSuccess =
  runCypherApiCypherPostResponse200 & {
    headers: Headers;
  };
export type runCypherApiCypherPostResponseError =
  runCypherApiCypherPostResponse422 & {
    headers: Headers;
  };

export type runCypherApiCypherPostResponse =
  | runCypherApiCypherPostResponseSuccess
  | runCypherApiCypherPostResponseError;

export const getRunCypherApiCypherPostUrl = () => {
  return `/api/cypher`;
};

export const runCypherApiCypherPost = async (
  runCypherApiCypherPostBody: RunCypherApiCypherPostBody,
  options?: RequestInit
): Promise<runCypherApiCypherPostResponse> => {
  return customFetch<runCypherApiCypherPostResponse>(
    getRunCypherApiCypherPostUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(runCypherApiCypherPostBody)
    }
  );
};

/**
 * NL2Cypher — 自然语言或 Cypher 直接查询
 * @summary Ask Graph
 */
export type askGraphApiAskPostResponse200 = {
  data: unknown;
  status: 200;
};

export type askGraphApiAskPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type askGraphApiAskPostResponseSuccess =
  askGraphApiAskPostResponse200 & {
    headers: Headers;
  };
export type askGraphApiAskPostResponseError = askGraphApiAskPostResponse422 & {
  headers: Headers;
};

export type askGraphApiAskPostResponse =
  | askGraphApiAskPostResponseSuccess
  | askGraphApiAskPostResponseError;

export const getAskGraphApiAskPostUrl = () => {
  return `/api/ask`;
};

export const askGraphApiAskPost = async (
  askRequest: AskRequest,
  options?: RequestInit
): Promise<askGraphApiAskPostResponse> => {
  return customFetch<askGraphApiAskPostResponse>(getAskGraphApiAskPostUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(askRequest)
  });
};
