/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Baize API
 * OpenAPI spec version: 1.0.0
 */
import type {
  HTTPValidationError,
  ListTasksApiV1TasksGetParams,
  TaskCreate,
  TaskListResponse,
  TaskResponse,
  TaskUpdate
} from '../baizeAPI.schemas';

import { customFetch } from '.././custom-fetch';

/**
 * Create a new task for the authenticated user.

Returns:
    TaskResponse with status 201. source is always set to 'manual'.

Raises:
    HTTPException: 401 if not authenticated.
 * @summary Create Task
 */
export type createTaskApiV1TasksPostResponse201 = {
  data: TaskResponse;
  status: 201;
};

export type createTaskApiV1TasksPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createTaskApiV1TasksPostResponseSuccess =
  createTaskApiV1TasksPostResponse201 & {
    headers: Headers;
  };
export type createTaskApiV1TasksPostResponseError =
  createTaskApiV1TasksPostResponse422 & {
    headers: Headers;
  };

export type createTaskApiV1TasksPostResponse =
  | createTaskApiV1TasksPostResponseSuccess
  | createTaskApiV1TasksPostResponseError;

export const getCreateTaskApiV1TasksPostUrl = () => {
  return `/api/v1/tasks`;
};

export const createTaskApiV1TasksPost = async (
  taskCreate: TaskCreate,
  options?: RequestInit
): Promise<createTaskApiV1TasksPostResponse> => {
  return customFetch<createTaskApiV1TasksPostResponse>(
    getCreateTaskApiV1TasksPostUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(taskCreate)
    }
  );
};

/**
 * Return paginated tasks for the authenticated user.

Returns:
    TaskListResponse with items and total count.

Raises:
    HTTPException: 401 if not authenticated.
 * @summary List Tasks
 */
export type listTasksApiV1TasksGetResponse200 = {
  data: TaskListResponse;
  status: 200;
};

export type listTasksApiV1TasksGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type listTasksApiV1TasksGetResponseSuccess =
  listTasksApiV1TasksGetResponse200 & {
    headers: Headers;
  };
export type listTasksApiV1TasksGetResponseError =
  listTasksApiV1TasksGetResponse422 & {
    headers: Headers;
  };

export type listTasksApiV1TasksGetResponse =
  | listTasksApiV1TasksGetResponseSuccess
  | listTasksApiV1TasksGetResponseError;

export const getListTasksApiV1TasksGetUrl = (
  params?: ListTasksApiV1TasksGetParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/tasks?${stringifiedParams}`
    : `/api/v1/tasks`;
};

export const listTasksApiV1TasksGet = async (
  params?: ListTasksApiV1TasksGetParams,
  options?: RequestInit
): Promise<listTasksApiV1TasksGetResponse> => {
  return customFetch<listTasksApiV1TasksGetResponse>(
    getListTasksApiV1TasksGetUrl(params),
    {
      ...options,
      method: 'GET'
    }
  );
};

/**
 * Return a single task owned by the authenticated user.

Returns:
    TaskResponse with status 200.

Raises:
    HTTPException: 401 if not authenticated, 404 if not found, 403 if not owner.
 * @summary Get Task
 */
export type getTaskApiV1TasksTaskIdGetResponse200 = {
  data: TaskResponse;
  status: 200;
};

export type getTaskApiV1TasksTaskIdGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getTaskApiV1TasksTaskIdGetResponseSuccess =
  getTaskApiV1TasksTaskIdGetResponse200 & {
    headers: Headers;
  };
export type getTaskApiV1TasksTaskIdGetResponseError =
  getTaskApiV1TasksTaskIdGetResponse422 & {
    headers: Headers;
  };

export type getTaskApiV1TasksTaskIdGetResponse =
  | getTaskApiV1TasksTaskIdGetResponseSuccess
  | getTaskApiV1TasksTaskIdGetResponseError;

export const getGetTaskApiV1TasksTaskIdGetUrl = (taskId: string) => {
  return `/api/v1/tasks/${taskId}`;
};

export const getTaskApiV1TasksTaskIdGet = async (
  taskId: string,
  options?: RequestInit
): Promise<getTaskApiV1TasksTaskIdGetResponse> => {
  return customFetch<getTaskApiV1TasksTaskIdGetResponse>(
    getGetTaskApiV1TasksTaskIdGetUrl(taskId),
    {
      ...options,
      method: 'GET'
    }
  );
};

/**
 * Partially update a task owned by the authenticated user.

When status is set to 'done', completed_at is automatically populated.

Returns:
    Updated TaskResponse.

Raises:
    HTTPException: 401 if not authenticated, 404 if not found, 403 if not owner.
 * @summary Update Task
 */
export type updateTaskApiV1TasksTaskIdPatchResponse200 = {
  data: TaskResponse;
  status: 200;
};

export type updateTaskApiV1TasksTaskIdPatchResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type updateTaskApiV1TasksTaskIdPatchResponseSuccess =
  updateTaskApiV1TasksTaskIdPatchResponse200 & {
    headers: Headers;
  };
export type updateTaskApiV1TasksTaskIdPatchResponseError =
  updateTaskApiV1TasksTaskIdPatchResponse422 & {
    headers: Headers;
  };

export type updateTaskApiV1TasksTaskIdPatchResponse =
  | updateTaskApiV1TasksTaskIdPatchResponseSuccess
  | updateTaskApiV1TasksTaskIdPatchResponseError;

export const getUpdateTaskApiV1TasksTaskIdPatchUrl = (taskId: string) => {
  return `/api/v1/tasks/${taskId}`;
};

export const updateTaskApiV1TasksTaskIdPatch = async (
  taskId: string,
  taskUpdate: TaskUpdate,
  options?: RequestInit
): Promise<updateTaskApiV1TasksTaskIdPatchResponse> => {
  return customFetch<updateTaskApiV1TasksTaskIdPatchResponse>(
    getUpdateTaskApiV1TasksTaskIdPatchUrl(taskId),
    {
      ...options,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(taskUpdate)
    }
  );
};

/**
 * Delete a task owned by the authenticated user.

Returns:
    204 No Content.

Raises:
    HTTPException: 401 if not authenticated, 404 if not found, 403 if not owner.
 * @summary Delete Task
 */
export type deleteTaskApiV1TasksTaskIdDeleteResponse204 = {
  data: void;
  status: 204;
};

export type deleteTaskApiV1TasksTaskIdDeleteResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type deleteTaskApiV1TasksTaskIdDeleteResponseSuccess =
  deleteTaskApiV1TasksTaskIdDeleteResponse204 & {
    headers: Headers;
  };
export type deleteTaskApiV1TasksTaskIdDeleteResponseError =
  deleteTaskApiV1TasksTaskIdDeleteResponse422 & {
    headers: Headers;
  };

export type deleteTaskApiV1TasksTaskIdDeleteResponse =
  | deleteTaskApiV1TasksTaskIdDeleteResponseSuccess
  | deleteTaskApiV1TasksTaskIdDeleteResponseError;

export const getDeleteTaskApiV1TasksTaskIdDeleteUrl = (taskId: string) => {
  return `/api/v1/tasks/${taskId}`;
};

export const deleteTaskApiV1TasksTaskIdDelete = async (
  taskId: string,
  options?: RequestInit
): Promise<deleteTaskApiV1TasksTaskIdDeleteResponse> => {
  return customFetch<deleteTaskApiV1TasksTaskIdDeleteResponse>(
    getDeleteTaskApiV1TasksTaskIdDeleteUrl(taskId),
    {
      ...options,
      method: 'DELETE'
    }
  );
};
