/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Baize API
 * OpenAPI spec version: 1.0.0
 */
import type {
  ChatCompletionRequest,
  ConversationCreateRequest,
  ConversationObject,
  HTTPValidationError,
  ModelListResponse,
  ResponsesRequest
} from '../baizeAPI.schemas';

import { customFetch } from '.././custom-fetch';

/**
 * Return all enabled agents as OpenAI-compatible model objects.
 * @summary List Models
 */
export type listModelsV1ModelsGetResponse200 = {
  data: ModelListResponse;
  status: 200;
};

export type listModelsV1ModelsGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type listModelsV1ModelsGetResponseSuccess =
  listModelsV1ModelsGetResponse200 & {
    headers: Headers;
  };
export type listModelsV1ModelsGetResponseError =
  listModelsV1ModelsGetResponse422 & {
    headers: Headers;
  };

export type listModelsV1ModelsGetResponse =
  | listModelsV1ModelsGetResponseSuccess
  | listModelsV1ModelsGetResponseError;

export const getListModelsV1ModelsGetUrl = () => {
  return `/v1/models`;
};

export const listModelsV1ModelsGet = async (
  options?: RequestInit
): Promise<listModelsV1ModelsGetResponse> => {
  return customFetch<listModelsV1ModelsGetResponse>(
    getListModelsV1ModelsGetUrl(),
    {
      ...options,
      method: 'GET'
    }
  );
};

/**
 * Create a response (OpenAI Responses API compatible).

Maps ``model`` to a Baize agent and ``conversation`` to a session.
Supports both streaming and non-streaming modes.
 * @summary Create Response
 */
export type createResponseV1ResponsesPostResponse200 = {
  data: unknown;
  status: 200;
};

export type createResponseV1ResponsesPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createResponseV1ResponsesPostResponseSuccess =
  createResponseV1ResponsesPostResponse200 & {
    headers: Headers;
  };
export type createResponseV1ResponsesPostResponseError =
  createResponseV1ResponsesPostResponse422 & {
    headers: Headers;
  };

export type createResponseV1ResponsesPostResponse =
  | createResponseV1ResponsesPostResponseSuccess
  | createResponseV1ResponsesPostResponseError;

export const getCreateResponseV1ResponsesPostUrl = () => {
  return `/v1/responses`;
};

export const createResponseV1ResponsesPost = async (
  responsesRequest: ResponsesRequest,
  options?: RequestInit
): Promise<createResponseV1ResponsesPostResponse> => {
  return customFetch<createResponseV1ResponsesPostResponse>(
    getCreateResponseV1ResponsesPostUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(responsesRequest)
    }
  );
};

/**
 * Create a new conversation (maps to a Baize session).

The conversation is created without an agent binding — the first
``POST /v1/responses`` call with this conversation will bind it.
 * @summary Create Conversation
 */
export type createConversationV1ConversationsPostResponse200 = {
  data: ConversationObject;
  status: 200;
};

export type createConversationV1ConversationsPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createConversationV1ConversationsPostResponseSuccess =
  createConversationV1ConversationsPostResponse200 & {
    headers: Headers;
  };
export type createConversationV1ConversationsPostResponseError =
  createConversationV1ConversationsPostResponse422 & {
    headers: Headers;
  };

export type createConversationV1ConversationsPostResponse =
  | createConversationV1ConversationsPostResponseSuccess
  | createConversationV1ConversationsPostResponseError;

export const getCreateConversationV1ConversationsPostUrl = () => {
  return `/v1/conversations`;
};

export const createConversationV1ConversationsPost = async (
  conversationCreateRequestNull: ConversationCreateRequest | null,
  options?: RequestInit
): Promise<createConversationV1ConversationsPostResponse> => {
  return customFetch<createConversationV1ConversationsPostResponse>(
    getCreateConversationV1ConversationsPostUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(conversationCreateRequestNull)
    }
  );
};

/**
 * Get conversation info (maps to a Baize session).
 * @summary Get Conversation
 */
export type getConversationV1ConversationsConversationIdGetResponse200 = {
  data: ConversationObject;
  status: 200;
};

export type getConversationV1ConversationsConversationIdGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getConversationV1ConversationsConversationIdGetResponseSuccess =
  getConversationV1ConversationsConversationIdGetResponse200 & {
    headers: Headers;
  };
export type getConversationV1ConversationsConversationIdGetResponseError =
  getConversationV1ConversationsConversationIdGetResponse422 & {
    headers: Headers;
  };

export type getConversationV1ConversationsConversationIdGetResponse =
  | getConversationV1ConversationsConversationIdGetResponseSuccess
  | getConversationV1ConversationsConversationIdGetResponseError;

export const getGetConversationV1ConversationsConversationIdGetUrl = (
  conversationId: string
) => {
  return `/v1/conversations/${conversationId}`;
};

export const getConversationV1ConversationsConversationIdGet = async (
  conversationId: string,
  options?: RequestInit
): Promise<getConversationV1ConversationsConversationIdGetResponse> => {
  return customFetch<getConversationV1ConversationsConversationIdGetResponse>(
    getGetConversationV1ConversationsConversationIdGetUrl(conversationId),
    {
      ...options,
      method: 'GET'
    }
  );
};

/**
 * OpenAI Chat Completions compatible endpoint (stateless).

The client sends the full message history in ``messages``.
Baize injects system prompt and memory but does NOT load session history.
 * @summary Chat Completions
 */
export type chatCompletionsV1ChatCompletionsPostResponse200 = {
  data: unknown;
  status: 200;
};

export type chatCompletionsV1ChatCompletionsPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type chatCompletionsV1ChatCompletionsPostResponseSuccess =
  chatCompletionsV1ChatCompletionsPostResponse200 & {
    headers: Headers;
  };
export type chatCompletionsV1ChatCompletionsPostResponseError =
  chatCompletionsV1ChatCompletionsPostResponse422 & {
    headers: Headers;
  };

export type chatCompletionsV1ChatCompletionsPostResponse =
  | chatCompletionsV1ChatCompletionsPostResponseSuccess
  | chatCompletionsV1ChatCompletionsPostResponseError;

export const getChatCompletionsV1ChatCompletionsPostUrl = () => {
  return `/v1/chat/completions`;
};

export const chatCompletionsV1ChatCompletionsPost = async (
  chatCompletionRequest: ChatCompletionRequest,
  options?: RequestInit
): Promise<chatCompletionsV1ChatCompletionsPostResponse> => {
  return customFetch<chatCompletionsV1ChatCompletionsPostResponse>(
    getChatCompletionsV1ChatCompletionsPostUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(chatCompletionRequest)
    }
  );
};
