/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Baize API
 * OpenAPI spec version: 1.0.0
 */
import type { HealthHealthGet200 } from '../baizeAPI.schemas';

import { customFetch } from '.././custom-fetch';

/**
 * Health check endpoint.
 * @summary Health
 */
export type healthHealthGetResponse200 = {
  data: HealthHealthGet200;
  status: 200;
};

export type healthHealthGetResponseSuccess = healthHealthGetResponse200 & {
  headers: Headers;
};
export type healthHealthGetResponse = healthHealthGetResponseSuccess;

export const getHealthHealthGetUrl = () => {
  return `/health`;
};

export const healthHealthGet = async (
  options?: RequestInit
): Promise<healthHealthGetResponse> => {
  return customFetch<healthHealthGetResponse>(getHealthHealthGetUrl(), {
    ...options,
    method: 'GET'
  });
};
