/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Baize API
 * OpenAPI spec version: 1.0.0
 */
import type {
  HTTPValidationError,
  LoginRequest,
  LogoutApiV1AuthLogoutPost200,
  TokenResponse
} from '../baizeAPI.schemas';

import { customFetch } from '.././custom-fetch';

/**
 * Authenticate a user and return a JWT access token.

Returns:
    TokenResponse with access_token, token_type, and expires_in.

Raises:
    HTTPException: 401 if credentials are invalid; 403 if account is inactive.
 * @summary Login
 */
export type loginApiV1AuthLoginPostResponse200 = {
  data: TokenResponse;
  status: 200;
};

export type loginApiV1AuthLoginPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type loginApiV1AuthLoginPostResponseSuccess =
  loginApiV1AuthLoginPostResponse200 & {
    headers: Headers;
  };
export type loginApiV1AuthLoginPostResponseError =
  loginApiV1AuthLoginPostResponse422 & {
    headers: Headers;
  };

export type loginApiV1AuthLoginPostResponse =
  | loginApiV1AuthLoginPostResponseSuccess
  | loginApiV1AuthLoginPostResponseError;

export const getLoginApiV1AuthLoginPostUrl = () => {
  return `/api/v1/auth/login`;
};

export const loginApiV1AuthLoginPost = async (
  loginRequest: LoginRequest,
  options?: RequestInit
): Promise<loginApiV1AuthLoginPostResponse> => {
  return customFetch<loginApiV1AuthLoginPostResponse>(
    getLoginApiV1AuthLoginPostUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(loginRequest)
    }
  );
};

/**
 * Revoke the current JWT, preventing further use.

Returns:
    Confirmation message on success.

Raises:
    HTTPException: 401 if the token is missing, malformed, or already invalid.
 * @summary Logout
 */
export type logoutApiV1AuthLogoutPostResponse200 = {
  data: LogoutApiV1AuthLogoutPost200;
  status: 200;
};

export type logoutApiV1AuthLogoutPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type logoutApiV1AuthLogoutPostResponseSuccess =
  logoutApiV1AuthLogoutPostResponse200 & {
    headers: Headers;
  };
export type logoutApiV1AuthLogoutPostResponseError =
  logoutApiV1AuthLogoutPostResponse422 & {
    headers: Headers;
  };

export type logoutApiV1AuthLogoutPostResponse =
  | logoutApiV1AuthLogoutPostResponseSuccess
  | logoutApiV1AuthLogoutPostResponseError;

export const getLogoutApiV1AuthLogoutPostUrl = () => {
  return `/api/v1/auth/logout`;
};

export const logoutApiV1AuthLogoutPost = async (
  options?: RequestInit
): Promise<logoutApiV1AuthLogoutPostResponse> => {
  return customFetch<logoutApiV1AuthLogoutPostResponse>(
    getLogoutApiV1AuthLogoutPostUrl(),
    {
      ...options,
      method: 'POST'
    }
  );
};

/**
 * Issue a new JWT and revoke the old one.

Returns:
    TokenResponse containing the new access token.

Raises:
    HTTPException: 401 if the token is missing, malformed, or already invalid.
 * @summary Refresh
 */
export type refreshApiV1AuthRefreshPostResponse200 = {
  data: TokenResponse;
  status: 200;
};

export type refreshApiV1AuthRefreshPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type refreshApiV1AuthRefreshPostResponseSuccess =
  refreshApiV1AuthRefreshPostResponse200 & {
    headers: Headers;
  };
export type refreshApiV1AuthRefreshPostResponseError =
  refreshApiV1AuthRefreshPostResponse422 & {
    headers: Headers;
  };

export type refreshApiV1AuthRefreshPostResponse =
  | refreshApiV1AuthRefreshPostResponseSuccess
  | refreshApiV1AuthRefreshPostResponseError;

export const getRefreshApiV1AuthRefreshPostUrl = () => {
  return `/api/v1/auth/refresh`;
};

export const refreshApiV1AuthRefreshPost = async (
  options?: RequestInit
): Promise<refreshApiV1AuthRefreshPostResponse> => {
  return customFetch<refreshApiV1AuthRefreshPostResponse>(
    getRefreshApiV1AuthRefreshPostUrl(),
    {
      ...options,
      method: 'POST'
    }
  );
};
