/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Baize API
 * OpenAPI spec version: 1.0.0
 */
import type {
  HTTPValidationError,
  ListMessagesApiV1SessionsSessionIdMessagesGetParams,
  ListSessionsApiV1AgentsAgentIdSessionsGetParams,
  MessageListResponse,
  SessionCreate,
  SessionListResponse,
  SessionResponse,
  SessionUpdate
} from '../baizeAPI.schemas';

import { customFetch } from '.././custom-fetch';

/**
 * Create a new session for the authenticated user under the given agent.

Returns:
    SessionResponse with status 201.

Raises:
    HTTPException: 401 if not authenticated.
 * @summary Create Session
 */
export type createSessionApiV1AgentsAgentIdSessionsPostResponse201 = {
  data: SessionResponse;
  status: 201;
};

export type createSessionApiV1AgentsAgentIdSessionsPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createSessionApiV1AgentsAgentIdSessionsPostResponseSuccess =
  createSessionApiV1AgentsAgentIdSessionsPostResponse201 & {
    headers: Headers;
  };
export type createSessionApiV1AgentsAgentIdSessionsPostResponseError =
  createSessionApiV1AgentsAgentIdSessionsPostResponse422 & {
    headers: Headers;
  };

export type createSessionApiV1AgentsAgentIdSessionsPostResponse =
  | createSessionApiV1AgentsAgentIdSessionsPostResponseSuccess
  | createSessionApiV1AgentsAgentIdSessionsPostResponseError;

export const getCreateSessionApiV1AgentsAgentIdSessionsPostUrl = (
  agentId: string
) => {
  return `/api/v1/agents/${agentId}/sessions`;
};

export const createSessionApiV1AgentsAgentIdSessionsPost = async (
  agentId: string,
  sessionCreate: SessionCreate,
  options?: RequestInit
): Promise<createSessionApiV1AgentsAgentIdSessionsPostResponse> => {
  return customFetch<createSessionApiV1AgentsAgentIdSessionsPostResponse>(
    getCreateSessionApiV1AgentsAgentIdSessionsPostUrl(agentId),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(sessionCreate)
    }
  );
};

/**
 * Return paginated sessions for the authenticated user under the given agent.

Sessions are ordered by updated_at descending.

Returns:
    SessionListResponse with items and total count.

Raises:
    HTTPException: 401 if not authenticated.
 * @summary List Sessions
 */
export type listSessionsApiV1AgentsAgentIdSessionsGetResponse200 = {
  data: SessionListResponse;
  status: 200;
};

export type listSessionsApiV1AgentsAgentIdSessionsGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type listSessionsApiV1AgentsAgentIdSessionsGetResponseSuccess =
  listSessionsApiV1AgentsAgentIdSessionsGetResponse200 & {
    headers: Headers;
  };
export type listSessionsApiV1AgentsAgentIdSessionsGetResponseError =
  listSessionsApiV1AgentsAgentIdSessionsGetResponse422 & {
    headers: Headers;
  };

export type listSessionsApiV1AgentsAgentIdSessionsGetResponse =
  | listSessionsApiV1AgentsAgentIdSessionsGetResponseSuccess
  | listSessionsApiV1AgentsAgentIdSessionsGetResponseError;

export const getListSessionsApiV1AgentsAgentIdSessionsGetUrl = (
  agentId: string,
  params?: ListSessionsApiV1AgentsAgentIdSessionsGetParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/agents/${agentId}/sessions?${stringifiedParams}`
    : `/api/v1/agents/${agentId}/sessions`;
};

export const listSessionsApiV1AgentsAgentIdSessionsGet = async (
  agentId: string,
  params?: ListSessionsApiV1AgentsAgentIdSessionsGetParams,
  options?: RequestInit
): Promise<listSessionsApiV1AgentsAgentIdSessionsGetResponse> => {
  return customFetch<listSessionsApiV1AgentsAgentIdSessionsGetResponse>(
    getListSessionsApiV1AgentsAgentIdSessionsGetUrl(agentId, params),
    {
      ...options,
      method: 'GET'
    }
  );
};

/**
 * Return a single session owned by the authenticated user.

Returns:
    SessionResponse with status 200.

Raises:
    HTTPException: 401 if not authenticated, 404 if not found, 403 if not owner.
 * @summary Get Session
 */
export type getSessionApiV1SessionsSessionIdGetResponse200 = {
  data: SessionResponse;
  status: 200;
};

export type getSessionApiV1SessionsSessionIdGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getSessionApiV1SessionsSessionIdGetResponseSuccess =
  getSessionApiV1SessionsSessionIdGetResponse200 & {
    headers: Headers;
  };
export type getSessionApiV1SessionsSessionIdGetResponseError =
  getSessionApiV1SessionsSessionIdGetResponse422 & {
    headers: Headers;
  };

export type getSessionApiV1SessionsSessionIdGetResponse =
  | getSessionApiV1SessionsSessionIdGetResponseSuccess
  | getSessionApiV1SessionsSessionIdGetResponseError;

export const getGetSessionApiV1SessionsSessionIdGetUrl = (
  sessionId: string
) => {
  return `/api/v1/sessions/${sessionId}`;
};

export const getSessionApiV1SessionsSessionIdGet = async (
  sessionId: string,
  options?: RequestInit
): Promise<getSessionApiV1SessionsSessionIdGetResponse> => {
  return customFetch<getSessionApiV1SessionsSessionIdGetResponse>(
    getGetSessionApiV1SessionsSessionIdGetUrl(sessionId),
    {
      ...options,
      method: 'GET'
    }
  );
};

/**
 * Update a session (title and/or status).

Returns:
    SessionResponse with updated fields.

Raises:
    HTTPException: 401 if not authenticated, 403 if not owner.
 * @summary Update Session
 */
export type updateSessionApiV1SessionsSessionIdPatchResponse200 = {
  data: SessionResponse;
  status: 200;
};

export type updateSessionApiV1SessionsSessionIdPatchResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type updateSessionApiV1SessionsSessionIdPatchResponseSuccess =
  updateSessionApiV1SessionsSessionIdPatchResponse200 & {
    headers: Headers;
  };
export type updateSessionApiV1SessionsSessionIdPatchResponseError =
  updateSessionApiV1SessionsSessionIdPatchResponse422 & {
    headers: Headers;
  };

export type updateSessionApiV1SessionsSessionIdPatchResponse =
  | updateSessionApiV1SessionsSessionIdPatchResponseSuccess
  | updateSessionApiV1SessionsSessionIdPatchResponseError;

export const getUpdateSessionApiV1SessionsSessionIdPatchUrl = (
  sessionId: string
) => {
  return `/api/v1/sessions/${sessionId}`;
};

export const updateSessionApiV1SessionsSessionIdPatch = async (
  sessionId: string,
  sessionUpdate: SessionUpdate,
  options?: RequestInit
): Promise<updateSessionApiV1SessionsSessionIdPatchResponse> => {
  return customFetch<updateSessionApiV1SessionsSessionIdPatchResponse>(
    getUpdateSessionApiV1SessionsSessionIdPatchUrl(sessionId),
    {
      ...options,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(sessionUpdate)
    }
  );
};

/**
 * Delete a session owned by the authenticated user.

Returns:
    204 No Content.

Raises:
    HTTPException: 401 if not authenticated, 403 if not owner.
 * @summary Delete Session
 */
export type deleteSessionApiV1SessionsSessionIdDeleteResponse204 = {
  data: void;
  status: 204;
};

export type deleteSessionApiV1SessionsSessionIdDeleteResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type deleteSessionApiV1SessionsSessionIdDeleteResponseSuccess =
  deleteSessionApiV1SessionsSessionIdDeleteResponse204 & {
    headers: Headers;
  };
export type deleteSessionApiV1SessionsSessionIdDeleteResponseError =
  deleteSessionApiV1SessionsSessionIdDeleteResponse422 & {
    headers: Headers;
  };

export type deleteSessionApiV1SessionsSessionIdDeleteResponse =
  | deleteSessionApiV1SessionsSessionIdDeleteResponseSuccess
  | deleteSessionApiV1SessionsSessionIdDeleteResponseError;

export const getDeleteSessionApiV1SessionsSessionIdDeleteUrl = (
  sessionId: string
) => {
  return `/api/v1/sessions/${sessionId}`;
};

export const deleteSessionApiV1SessionsSessionIdDelete = async (
  sessionId: string,
  options?: RequestInit
): Promise<deleteSessionApiV1SessionsSessionIdDeleteResponse> => {
  return customFetch<deleteSessionApiV1SessionsSessionIdDeleteResponse>(
    getDeleteSessionApiV1SessionsSessionIdDeleteUrl(sessionId),
    {
      ...options,
      method: 'DELETE'
    }
  );
};

/**
 * Return paginated messages for a session owned by the authenticated user.

Supports two pagination modes:
- **before**: Cursor-based — return ``limit`` messages older than this message ID.
  Used for "load earlier" when scrolling up in chat UI.
- **offset**: Traditional offset pagination.

Messages are always returned in chronological order (oldest first).

Returns:
    MessageListResponse with items and total count.

Raises:
    HTTPException: 401 if not authenticated, 404 if session not found, 403 if not owner.
 * @summary List Messages
 */
export type listMessagesApiV1SessionsSessionIdMessagesGetResponse200 = {
  data: MessageListResponse;
  status: 200;
};

export type listMessagesApiV1SessionsSessionIdMessagesGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type listMessagesApiV1SessionsSessionIdMessagesGetResponseSuccess =
  listMessagesApiV1SessionsSessionIdMessagesGetResponse200 & {
    headers: Headers;
  };
export type listMessagesApiV1SessionsSessionIdMessagesGetResponseError =
  listMessagesApiV1SessionsSessionIdMessagesGetResponse422 & {
    headers: Headers;
  };

export type listMessagesApiV1SessionsSessionIdMessagesGetResponse =
  | listMessagesApiV1SessionsSessionIdMessagesGetResponseSuccess
  | listMessagesApiV1SessionsSessionIdMessagesGetResponseError;

export const getListMessagesApiV1SessionsSessionIdMessagesGetUrl = (
  sessionId: string,
  params?: ListMessagesApiV1SessionsSessionIdMessagesGetParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/sessions/${sessionId}/messages?${stringifiedParams}`
    : `/api/v1/sessions/${sessionId}/messages`;
};

export const listMessagesApiV1SessionsSessionIdMessagesGet = async (
  sessionId: string,
  params?: ListMessagesApiV1SessionsSessionIdMessagesGetParams,
  options?: RequestInit
): Promise<listMessagesApiV1SessionsSessionIdMessagesGetResponse> => {
  return customFetch<listMessagesApiV1SessionsSessionIdMessagesGetResponse>(
    getListMessagesApiV1SessionsSessionIdMessagesGetUrl(sessionId, params),
    {
      ...options,
      method: 'GET'
    }
  );
};
