/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Baize API
 * OpenAPI spec version: 1.0.0
 */
import type {
  AgentCreate,
  AgentResponse,
  AgentUpdate,
  HTTPValidationError
} from '../baizeAPI.schemas';

import { customFetch } from '.././custom-fetch';

/**
 * Create a new agent configuration for the authenticated user.

Returns:
    AgentResponse with status 201.

Raises:
    HTTPException: 401 if not authenticated, 400 if tools are invalid.
 * @summary Create Agent
 */
export type createAgentApiV1AgentsPostResponse201 = {
  data: AgentResponse;
  status: 201;
};

export type createAgentApiV1AgentsPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createAgentApiV1AgentsPostResponseSuccess =
  createAgentApiV1AgentsPostResponse201 & {
    headers: Headers;
  };
export type createAgentApiV1AgentsPostResponseError =
  createAgentApiV1AgentsPostResponse422 & {
    headers: Headers;
  };

export type createAgentApiV1AgentsPostResponse =
  | createAgentApiV1AgentsPostResponseSuccess
  | createAgentApiV1AgentsPostResponseError;

export const getCreateAgentApiV1AgentsPostUrl = () => {
  return `/api/v1/agents`;
};

export const createAgentApiV1AgentsPost = async (
  agentCreate: AgentCreate,
  options?: RequestInit
): Promise<createAgentApiV1AgentsPostResponse> => {
  return customFetch<createAgentApiV1AgentsPostResponse>(
    getCreateAgentApiV1AgentsPostUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(agentCreate)
    }
  );
};

/**
 * Return all agent configurations owned by the authenticated user.

Returns:
    List of AgentResponse with status 200.

Raises:
    HTTPException: 401 if not authenticated.
 * @summary List Agents
 */
export type listAgentsApiV1AgentsGetResponse200 = {
  data: AgentResponse[];
  status: 200;
};

export type listAgentsApiV1AgentsGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type listAgentsApiV1AgentsGetResponseSuccess =
  listAgentsApiV1AgentsGetResponse200 & {
    headers: Headers;
  };
export type listAgentsApiV1AgentsGetResponseError =
  listAgentsApiV1AgentsGetResponse422 & {
    headers: Headers;
  };

export type listAgentsApiV1AgentsGetResponse =
  | listAgentsApiV1AgentsGetResponseSuccess
  | listAgentsApiV1AgentsGetResponseError;

export const getListAgentsApiV1AgentsGetUrl = () => {
  return `/api/v1/agents`;
};

export const listAgentsApiV1AgentsGet = async (
  options?: RequestInit
): Promise<listAgentsApiV1AgentsGetResponse> => {
  return customFetch<listAgentsApiV1AgentsGetResponse>(
    getListAgentsApiV1AgentsGetUrl(),
    {
      ...options,
      method: 'GET'
    }
  );
};

/**
 * Return a single agent configuration owned by the authenticated user.

Returns:
    AgentResponse with status 200.

Raises:
    HTTPException: 401 if not authenticated, 404 if not found or not owned.
 * @summary Get Agent
 */
export type getAgentApiV1AgentsAgentIdGetResponse200 = {
  data: AgentResponse;
  status: 200;
};

export type getAgentApiV1AgentsAgentIdGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getAgentApiV1AgentsAgentIdGetResponseSuccess =
  getAgentApiV1AgentsAgentIdGetResponse200 & {
    headers: Headers;
  };
export type getAgentApiV1AgentsAgentIdGetResponseError =
  getAgentApiV1AgentsAgentIdGetResponse422 & {
    headers: Headers;
  };

export type getAgentApiV1AgentsAgentIdGetResponse =
  | getAgentApiV1AgentsAgentIdGetResponseSuccess
  | getAgentApiV1AgentsAgentIdGetResponseError;

export const getGetAgentApiV1AgentsAgentIdGetUrl = (agentId: string) => {
  return `/api/v1/agents/${agentId}`;
};

export const getAgentApiV1AgentsAgentIdGet = async (
  agentId: string,
  options?: RequestInit
): Promise<getAgentApiV1AgentsAgentIdGetResponse> => {
  return customFetch<getAgentApiV1AgentsAgentIdGetResponse>(
    getGetAgentApiV1AgentsAgentIdGetUrl(agentId),
    {
      ...options,
      method: 'GET'
    }
  );
};

/**
 * Partially update an agent configuration owned by the authenticated user.

Returns:
    Updated AgentResponse with status 200.

Raises:
    HTTPException: 401 if not authenticated, 404 if not found, 400 if tools invalid.
 * @summary Update Agent
 */
export type updateAgentApiV1AgentsAgentIdPutResponse200 = {
  data: AgentResponse;
  status: 200;
};

export type updateAgentApiV1AgentsAgentIdPutResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type updateAgentApiV1AgentsAgentIdPutResponseSuccess =
  updateAgentApiV1AgentsAgentIdPutResponse200 & {
    headers: Headers;
  };
export type updateAgentApiV1AgentsAgentIdPutResponseError =
  updateAgentApiV1AgentsAgentIdPutResponse422 & {
    headers: Headers;
  };

export type updateAgentApiV1AgentsAgentIdPutResponse =
  | updateAgentApiV1AgentsAgentIdPutResponseSuccess
  | updateAgentApiV1AgentsAgentIdPutResponseError;

export const getUpdateAgentApiV1AgentsAgentIdPutUrl = (agentId: string) => {
  return `/api/v1/agents/${agentId}`;
};

export const updateAgentApiV1AgentsAgentIdPut = async (
  agentId: string,
  agentUpdate: AgentUpdate,
  options?: RequestInit
): Promise<updateAgentApiV1AgentsAgentIdPutResponse> => {
  return customFetch<updateAgentApiV1AgentsAgentIdPutResponse>(
    getUpdateAgentApiV1AgentsAgentIdPutUrl(agentId),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(agentUpdate)
    }
  );
};

/**
 * Delete an agent configuration owned by the authenticated user.

Returns:
    204 No Content.

Raises:
    HTTPException: 401 if not authenticated, 404 if not found, 400 if default agent.
 * @summary Delete Agent
 */
export type deleteAgentApiV1AgentsAgentIdDeleteResponse204 = {
  data: void;
  status: 204;
};

export type deleteAgentApiV1AgentsAgentIdDeleteResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type deleteAgentApiV1AgentsAgentIdDeleteResponseSuccess =
  deleteAgentApiV1AgentsAgentIdDeleteResponse204 & {
    headers: Headers;
  };
export type deleteAgentApiV1AgentsAgentIdDeleteResponseError =
  deleteAgentApiV1AgentsAgentIdDeleteResponse422 & {
    headers: Headers;
  };

export type deleteAgentApiV1AgentsAgentIdDeleteResponse =
  | deleteAgentApiV1AgentsAgentIdDeleteResponseSuccess
  | deleteAgentApiV1AgentsAgentIdDeleteResponseError;

export const getDeleteAgentApiV1AgentsAgentIdDeleteUrl = (agentId: string) => {
  return `/api/v1/agents/${agentId}`;
};

export const deleteAgentApiV1AgentsAgentIdDelete = async (
  agentId: string,
  options?: RequestInit
): Promise<deleteAgentApiV1AgentsAgentIdDeleteResponse> => {
  return customFetch<deleteAgentApiV1AgentsAgentIdDeleteResponse>(
    getDeleteAgentApiV1AgentsAgentIdDeleteUrl(agentId),
    {
      ...options,
      method: 'DELETE'
    }
  );
};
