/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Baize API
 * OpenAPI spec version: 1.0.0
 */
import type {
  HTTPValidationError,
  ListProvidersApiV1LlmProvidersGet200Item,
  TestRequest,
  TestResponse
} from '../baizeAPI.schemas';

import { customFetch } from '.././custom-fetch';

/**
 * Return all configured LLM providers with their availability status.

Accessible by both authenticated users and internal services (Service Key).
Sensitive fields (api_key, base_url) are excluded from the response.

Returns:
    List of provider info dicts with name, type, status, and models.

Raises:
    HTTPException: 401 if not authenticated.
 * @summary List Providers
 */
export type listProvidersApiV1LlmProvidersGetResponse200 = {
  data: ListProvidersApiV1LlmProvidersGet200Item[];
  status: 200;
};

export type listProvidersApiV1LlmProvidersGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type listProvidersApiV1LlmProvidersGetResponseSuccess =
  listProvidersApiV1LlmProvidersGetResponse200 & {
    headers: Headers;
  };
export type listProvidersApiV1LlmProvidersGetResponseError =
  listProvidersApiV1LlmProvidersGetResponse422 & {
    headers: Headers;
  };

export type listProvidersApiV1LlmProvidersGetResponse =
  | listProvidersApiV1LlmProvidersGetResponseSuccess
  | listProvidersApiV1LlmProvidersGetResponseError;

export const getListProvidersApiV1LlmProvidersGetUrl = () => {
  return `/api/v1/llm/providers`;
};

export const listProvidersApiV1LlmProvidersGet = async (
  options?: RequestInit
): Promise<listProvidersApiV1LlmProvidersGetResponse> => {
  return customFetch<listProvidersApiV1LlmProvidersGetResponse>(
    getListProvidersApiV1LlmProvidersGetUrl(),
    {
      ...options,
      method: 'GET'
    }
  );
};

/**
 * Test connectivity to a specific LLM provider/model by sending a ping message.

Returns a business-level result (HTTP 200 always); errors are encoded in the
response body rather than as HTTP error status codes.

Args:
    body: Provider name and model ID to test.

Returns:
    TestResponse with success=True and latency_ms on success,
    or success=False and error message on failure.

Raises:
    HTTPException: 401 if not authenticated.
 * @summary Test Provider
 */
export type testProviderApiV1LlmTestPostResponse200 = {
  data: TestResponse;
  status: 200;
};

export type testProviderApiV1LlmTestPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type testProviderApiV1LlmTestPostResponseSuccess =
  testProviderApiV1LlmTestPostResponse200 & {
    headers: Headers;
  };
export type testProviderApiV1LlmTestPostResponseError =
  testProviderApiV1LlmTestPostResponse422 & {
    headers: Headers;
  };

export type testProviderApiV1LlmTestPostResponse =
  | testProviderApiV1LlmTestPostResponseSuccess
  | testProviderApiV1LlmTestPostResponseError;

export const getTestProviderApiV1LlmTestPostUrl = () => {
  return `/api/v1/llm/test`;
};

export const testProviderApiV1LlmTestPost = async (
  testRequest: TestRequest,
  options?: RequestInit
): Promise<testProviderApiV1LlmTestPostResponse> => {
  return customFetch<testProviderApiV1LlmTestPostResponse>(
    getTestProviderApiV1LlmTestPostUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(testRequest)
    }
  );
};
