/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * DiTing API
 * 代码知识图谱分析系统 — 多语言、Neo4j、FastAPI
 * OpenAPI spec version: 0.1.0
 */
export type AskRequestMode =
  (typeof AskRequestMode)[keyof typeof AskRequestMode];

export const AskRequestMode = {
  auto: 'auto',
  nl: 'nl',
  cypher: 'cypher'
} as const;

export interface AskRequest {
  question: string;
  mode?: AskRequestMode;
}

export interface CloneRequest {
  /** 若目标目录已存在则先删除 */
  force?: boolean;
}

export interface EnhanceRequest {
  clean?: boolean;
  verify?: boolean;
}

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export type ProjectScanStatus =
  (typeof ProjectScanStatus)[keyof typeof ProjectScanStatus];

export const ProjectScanStatus = {
  pending: 'pending',
  scanned: 'scanned',
  enhanced: 'enhanced',
  error: 'error'
} as const;

export type ProjectNodeStats = { [key: string]: number };

export interface Project {
  id: string;
  name: string;
  language: string;
  source_path: string;
  /** source_path 解析后的完整绝对路径 */
  resolved_path?: string | null;
  description?: string;
  repo_url?: string | null;
  branch?: string | null;
  scan_status?: ProjectScanStatus;
  scanned_at?: string | null;
  enhanced_at?: string | null;
  schema_version?: number;
  node_stats?: ProjectNodeStats;
}

export interface PageProject {
  items: Project[];
  /** @minimum 0 */
  total: number;
  /** @minimum 1 */
  page: number;
  /** @minimum 1 */
  size: number;
  /** @minimum 0 */
  pages: number;
}

export type PageDictStrAnyItemsItem = { [key: string]: unknown };

export interface PageDictStrAny {
  items: PageDictStrAnyItemsItem[];
  /** @minimum 0 */
  total: number;
  /** @minimum 1 */
  page: number;
  /** @minimum 1 */
  size: number;
  /** @minimum 0 */
  pages: number;
}

/**
 * 编程语言
 */
export type ProjectCreateLanguage =
  (typeof ProjectCreateLanguage)[keyof typeof ProjectCreateLanguage];

export const ProjectCreateLanguage = {
  java: 'java',
  python: 'python'
} as const;

export interface ProjectCreate {
  /** 项目唯一 ID（如 order-service） */
  id: string;
  /** 可读名称，默认同 id */
  name?: string;
  /** 编程语言 */
  language: ProjectCreateLanguage;
  /** 源码根目录：绝对路径或相对 DITING_WORKSPACE 的相对路径 */
  source_path: string;
  description?: string;
  /** Git 仓库 URL（github/gitee 等） */
  repo_url?: string | null;
  /** 默认分支，留空自动使用仓库默认分支 */
  branch?: string | null;
}

export interface ProjectUpdate {
  name?: string | null;
  source_path?: string | null;
  description?: string | null;
  repo_url?: string | null;
  branch?: string | null;
  project_type?: string | null;
}

export interface ScanRequest {
  reset?: boolean;
  skip_enhance?: boolean;
}

export type ListProjectsApiProjectsGetParams = {
  /**
   * Page number
   * @minimum 1
   */
  page?: number;
  /**
   * Page size
   * @minimum 1
   * @maximum 100
   */
  size?: number;
};

export type SearchCodeApiSearchGetParams = {
  /**
   * 搜索关键词
   */
  q: string;
  /**
   * all | class | method | function
   */
  scope?: string;
  /**
   * @minimum 1
   * @maximum 200
   */
  limit?: number;
  /**
   * 项目 ID，不传则查全部
   */
  project?: string | null;
  /**
   * Page number
   * @minimum 1
   */
  page?: number;
  /**
   * Page size
   * @minimum 1
   * @maximum 100
   */
  size?: number;
};

export type GetClassInfoApiClassesClassFqnGetParams = {
  project?: string | null;
  /**
   * 语言插件
   */
  language?: string;
};

export type TraceCallChainApiMethodsMethodIdCallChainGetParams = {
  /**
   * callees | callers
   */
  direction?: string;
  /**
   * @minimum 1
   * @maximum 5
   */
  depth?: number;
  project?: string | null;
  language?: string;
};

export type GetMethodInfoApiMethodsMethodIdGetParams = {
  project?: string | null;
  language?: string;
};

export type FindSpringBeansApiJavaSpringBeansGetParams = {
  stereotype?: string;
  name?: string | null;
  /**
   * @minimum 1
   * @maximum 200
   */
  limit?: number;
  project?: string | null;
  /**
   * Page number
   * @minimum 1
   */
  page?: number;
  /**
   * Page size
   * @minimum 1
   * @maximum 100
   */
  size?: number;
};

export type FindApiEndpointsApiJavaApiEndpointsGetParams = {
  name?: string | null;
  /**
   * @minimum 1
   * @maximum 200
   */
  limit?: number;
  project?: string | null;
  /**
   * Page number
   * @minimum 1
   */
  page?: number;
  /**
   * Page size
   * @minimum 1
   * @maximum 100
   */
  size?: number;
};

export type FindImplementationsApiJavaImplementationsInterfaceFqnGetParams = {
  project?: string | null;
};

export type RunCypherApiCypherPostBody = { [key: string]: unknown };
