/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * DiTing API
 * 代码知识图谱分析系统 — 多语言、Neo4j、FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type {
  FindApiEndpointsApiJavaApiEndpointsGetParams,
  FindImplementationsApiJavaImplementationsInterfaceFqnGetParams,
  FindSpringBeansApiJavaSpringBeansGetParams,
  GetClassInfoApiClassesClassFqnGetParams,
  GetMethodInfoApiMethodsMethodIdGetParams,
  HTTPValidationError,
  PageDictStrAny,
  SearchCodeApiSearchGetParams,
  TraceCallChainApiMethodsMethodIdCallChainGetParams
} from '../diTingAPI.schemas';

import { customFetch } from '.././custom-fetch';

/**
 * @summary Search Code
 */
export type searchCodeApiSearchGetResponse200 = {
  data: PageDictStrAny;
  status: 200;
};

export type searchCodeApiSearchGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type searchCodeApiSearchGetResponseSuccess =
  searchCodeApiSearchGetResponse200 & {
    headers: Headers;
  };
export type searchCodeApiSearchGetResponseError =
  searchCodeApiSearchGetResponse422 & {
    headers: Headers;
  };

export type searchCodeApiSearchGetResponse =
  | searchCodeApiSearchGetResponseSuccess
  | searchCodeApiSearchGetResponseError;

export const getSearchCodeApiSearchGetUrl = (
  params: SearchCodeApiSearchGetParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/search?${stringifiedParams}`
    : `/api/search`;
};

export const searchCodeApiSearchGet = async (
  params: SearchCodeApiSearchGetParams,
  options?: RequestInit
): Promise<searchCodeApiSearchGetResponse> => {
  return customFetch<searchCodeApiSearchGetResponse>(
    getSearchCodeApiSearchGetUrl(params),
    {
      ...options,
      method: 'GET'
    }
  );
};

/**
 * @summary Get Class Info
 */
export type getClassInfoApiClassesClassFqnGetResponse200 = {
  data: unknown;
  status: 200;
};

export type getClassInfoApiClassesClassFqnGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getClassInfoApiClassesClassFqnGetResponseSuccess =
  getClassInfoApiClassesClassFqnGetResponse200 & {
    headers: Headers;
  };
export type getClassInfoApiClassesClassFqnGetResponseError =
  getClassInfoApiClassesClassFqnGetResponse422 & {
    headers: Headers;
  };

export type getClassInfoApiClassesClassFqnGetResponse =
  | getClassInfoApiClassesClassFqnGetResponseSuccess
  | getClassInfoApiClassesClassFqnGetResponseError;

export const getGetClassInfoApiClassesClassFqnGetUrl = (
  classFqn: string,
  params?: GetClassInfoApiClassesClassFqnGetParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/classes/${classFqn}?${stringifiedParams}`
    : `/api/classes/${classFqn}`;
};

export const getClassInfoApiClassesClassFqnGet = async (
  classFqn: string,
  params?: GetClassInfoApiClassesClassFqnGetParams,
  options?: RequestInit
): Promise<getClassInfoApiClassesClassFqnGetResponse> => {
  return customFetch<getClassInfoApiClassesClassFqnGetResponse>(
    getGetClassInfoApiClassesClassFqnGetUrl(classFqn, params),
    {
      ...options,
      method: 'GET'
    }
  );
};

/**
 * @summary Trace Call Chain
 */
export type traceCallChainApiMethodsMethodIdCallChainGetResponse200 = {
  data: unknown;
  status: 200;
};

export type traceCallChainApiMethodsMethodIdCallChainGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type traceCallChainApiMethodsMethodIdCallChainGetResponseSuccess =
  traceCallChainApiMethodsMethodIdCallChainGetResponse200 & {
    headers: Headers;
  };
export type traceCallChainApiMethodsMethodIdCallChainGetResponseError =
  traceCallChainApiMethodsMethodIdCallChainGetResponse422 & {
    headers: Headers;
  };

export type traceCallChainApiMethodsMethodIdCallChainGetResponse =
  | traceCallChainApiMethodsMethodIdCallChainGetResponseSuccess
  | traceCallChainApiMethodsMethodIdCallChainGetResponseError;

export const getTraceCallChainApiMethodsMethodIdCallChainGetUrl = (
  methodId: string,
  params?: TraceCallChainApiMethodsMethodIdCallChainGetParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/methods/${methodId}/call-chain?${stringifiedParams}`
    : `/api/methods/${methodId}/call-chain`;
};

export const traceCallChainApiMethodsMethodIdCallChainGet = async (
  methodId: string,
  params?: TraceCallChainApiMethodsMethodIdCallChainGetParams,
  options?: RequestInit
): Promise<traceCallChainApiMethodsMethodIdCallChainGetResponse> => {
  return customFetch<traceCallChainApiMethodsMethodIdCallChainGetResponse>(
    getTraceCallChainApiMethodsMethodIdCallChainGetUrl(methodId, params),
    {
      ...options,
      method: 'GET'
    }
  );
};

/**
 * @summary Get Method Info
 */
export type getMethodInfoApiMethodsMethodIdGetResponse200 = {
  data: unknown;
  status: 200;
};

export type getMethodInfoApiMethodsMethodIdGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getMethodInfoApiMethodsMethodIdGetResponseSuccess =
  getMethodInfoApiMethodsMethodIdGetResponse200 & {
    headers: Headers;
  };
export type getMethodInfoApiMethodsMethodIdGetResponseError =
  getMethodInfoApiMethodsMethodIdGetResponse422 & {
    headers: Headers;
  };

export type getMethodInfoApiMethodsMethodIdGetResponse =
  | getMethodInfoApiMethodsMethodIdGetResponseSuccess
  | getMethodInfoApiMethodsMethodIdGetResponseError;

export const getGetMethodInfoApiMethodsMethodIdGetUrl = (
  methodId: string,
  params?: GetMethodInfoApiMethodsMethodIdGetParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/methods/${methodId}?${stringifiedParams}`
    : `/api/methods/${methodId}`;
};

export const getMethodInfoApiMethodsMethodIdGet = async (
  methodId: string,
  params?: GetMethodInfoApiMethodsMethodIdGetParams,
  options?: RequestInit
): Promise<getMethodInfoApiMethodsMethodIdGetResponse> => {
  return customFetch<getMethodInfoApiMethodsMethodIdGetResponse>(
    getGetMethodInfoApiMethodsMethodIdGetUrl(methodId, params),
    {
      ...options,
      method: 'GET'
    }
  );
};

/**
 * @summary Find Spring Beans
 */
export type findSpringBeansApiJavaSpringBeansGetResponse200 = {
  data: PageDictStrAny;
  status: 200;
};

export type findSpringBeansApiJavaSpringBeansGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type findSpringBeansApiJavaSpringBeansGetResponseSuccess =
  findSpringBeansApiJavaSpringBeansGetResponse200 & {
    headers: Headers;
  };
export type findSpringBeansApiJavaSpringBeansGetResponseError =
  findSpringBeansApiJavaSpringBeansGetResponse422 & {
    headers: Headers;
  };

export type findSpringBeansApiJavaSpringBeansGetResponse =
  | findSpringBeansApiJavaSpringBeansGetResponseSuccess
  | findSpringBeansApiJavaSpringBeansGetResponseError;

export const getFindSpringBeansApiJavaSpringBeansGetUrl = (
  params?: FindSpringBeansApiJavaSpringBeansGetParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/java/spring-beans?${stringifiedParams}`
    : `/api/java/spring-beans`;
};

export const findSpringBeansApiJavaSpringBeansGet = async (
  params?: FindSpringBeansApiJavaSpringBeansGetParams,
  options?: RequestInit
): Promise<findSpringBeansApiJavaSpringBeansGetResponse> => {
  return customFetch<findSpringBeansApiJavaSpringBeansGetResponse>(
    getFindSpringBeansApiJavaSpringBeansGetUrl(params),
    {
      ...options,
      method: 'GET'
    }
  );
};

/**
 * @summary Find Api Endpoints
 */
export type findApiEndpointsApiJavaApiEndpointsGetResponse200 = {
  data: PageDictStrAny;
  status: 200;
};

export type findApiEndpointsApiJavaApiEndpointsGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type findApiEndpointsApiJavaApiEndpointsGetResponseSuccess =
  findApiEndpointsApiJavaApiEndpointsGetResponse200 & {
    headers: Headers;
  };
export type findApiEndpointsApiJavaApiEndpointsGetResponseError =
  findApiEndpointsApiJavaApiEndpointsGetResponse422 & {
    headers: Headers;
  };

export type findApiEndpointsApiJavaApiEndpointsGetResponse =
  | findApiEndpointsApiJavaApiEndpointsGetResponseSuccess
  | findApiEndpointsApiJavaApiEndpointsGetResponseError;

export const getFindApiEndpointsApiJavaApiEndpointsGetUrl = (
  params?: FindApiEndpointsApiJavaApiEndpointsGetParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/java/api-endpoints?${stringifiedParams}`
    : `/api/java/api-endpoints`;
};

export const findApiEndpointsApiJavaApiEndpointsGet = async (
  params?: FindApiEndpointsApiJavaApiEndpointsGetParams,
  options?: RequestInit
): Promise<findApiEndpointsApiJavaApiEndpointsGetResponse> => {
  return customFetch<findApiEndpointsApiJavaApiEndpointsGetResponse>(
    getFindApiEndpointsApiJavaApiEndpointsGetUrl(params),
    {
      ...options,
      method: 'GET'
    }
  );
};

/**
 * @summary Find Implementations
 */
export type findImplementationsApiJavaImplementationsInterfaceFqnGetResponse200 =
  {
    data: unknown;
    status: 200;
  };

export type findImplementationsApiJavaImplementationsInterfaceFqnGetResponse422 =
  {
    data: HTTPValidationError;
    status: 422;
  };

export type findImplementationsApiJavaImplementationsInterfaceFqnGetResponseSuccess =
  findImplementationsApiJavaImplementationsInterfaceFqnGetResponse200 & {
    headers: Headers;
  };
export type findImplementationsApiJavaImplementationsInterfaceFqnGetResponseError =
  findImplementationsApiJavaImplementationsInterfaceFqnGetResponse422 & {
    headers: Headers;
  };

export type findImplementationsApiJavaImplementationsInterfaceFqnGetResponse =
  | findImplementationsApiJavaImplementationsInterfaceFqnGetResponseSuccess
  | findImplementationsApiJavaImplementationsInterfaceFqnGetResponseError;

export const getFindImplementationsApiJavaImplementationsInterfaceFqnGetUrl = (
  interfaceFqn: string,
  params?: FindImplementationsApiJavaImplementationsInterfaceFqnGetParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/java/implementations/${interfaceFqn}?${stringifiedParams}`
    : `/api/java/implementations/${interfaceFqn}`;
};

export const findImplementationsApiJavaImplementationsInterfaceFqnGet = async (
  interfaceFqn: string,
  params?: FindImplementationsApiJavaImplementationsInterfaceFqnGetParams,
  options?: RequestInit
): Promise<findImplementationsApiJavaImplementationsInterfaceFqnGetResponse> => {
  return customFetch<findImplementationsApiJavaImplementationsInterfaceFqnGetResponse>(
    getFindImplementationsApiJavaImplementationsInterfaceFqnGetUrl(
      interfaceFqn,
      params
    ),
    {
      ...options,
      method: 'GET'
    }
  );
};
