/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Baize API
 * OpenAPI spec version: 1.0.0
 */
import type {
  HTTPValidationError,
  ListUsersApiV1UsersGetParams,
  ResetKeyResponse,
  UserCreateRequest,
  UserCreateResponse,
  UserListResponse,
  UserResponse,
  UserUpdateRequest
} from '../baizeAPI.schemas';

import { customFetch } from '.././custom-fetch';

/**
 * Return the current user's profile.

Returns:
    UserResponse without password or api_key_hash.

Raises:
    HTTPException: 401 if not authenticated.
 * @summary Get Me
 */
export type getMeApiV1UsersMeGetResponse200 = {
  data: UserResponse;
  status: 200;
};

export type getMeApiV1UsersMeGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getMeApiV1UsersMeGetResponseSuccess =
  getMeApiV1UsersMeGetResponse200 & {
    headers: Headers;
  };
export type getMeApiV1UsersMeGetResponseError =
  getMeApiV1UsersMeGetResponse422 & {
    headers: Headers;
  };

export type getMeApiV1UsersMeGetResponse =
  | getMeApiV1UsersMeGetResponseSuccess
  | getMeApiV1UsersMeGetResponseError;

export const getGetMeApiV1UsersMeGetUrl = () => {
  return `/api/v1/users/me`;
};

export const getMeApiV1UsersMeGet = async (
  options?: RequestInit
): Promise<getMeApiV1UsersMeGetResponse> => {
  return customFetch<getMeApiV1UsersMeGetResponse>(
    getGetMeApiV1UsersMeGetUrl(),
    {
      ...options,
      method: 'GET'
    }
  );
};

/**
 * Update the current user's profile.

Returns:
    Updated UserResponse.

Raises:
    HTTPException: 401 if not authenticated; 409 if name is taken.
 * @summary Update Me
 */
export type updateMeApiV1UsersMePatchResponse200 = {
  data: UserResponse;
  status: 200;
};

export type updateMeApiV1UsersMePatchResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type updateMeApiV1UsersMePatchResponseSuccess =
  updateMeApiV1UsersMePatchResponse200 & {
    headers: Headers;
  };
export type updateMeApiV1UsersMePatchResponseError =
  updateMeApiV1UsersMePatchResponse422 & {
    headers: Headers;
  };

export type updateMeApiV1UsersMePatchResponse =
  | updateMeApiV1UsersMePatchResponseSuccess
  | updateMeApiV1UsersMePatchResponseError;

export const getUpdateMeApiV1UsersMePatchUrl = () => {
  return `/api/v1/users/me`;
};

export const updateMeApiV1UsersMePatch = async (
  userUpdateRequest: UserUpdateRequest,
  options?: RequestInit
): Promise<updateMeApiV1UsersMePatchResponse> => {
  return customFetch<updateMeApiV1UsersMePatchResponse>(
    getUpdateMeApiV1UsersMePatchUrl(),
    {
      ...options,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(userUpdateRequest)
    }
  );
};

/**
 * Create a new user (admin only).

Returns:
    UserCreateResponse with one-time plaintext api_key.

Raises:
    HTTPException: 401 if not authenticated; 403 if not admin.
 * @summary Create User
 */
export type createUserApiV1UsersPostResponse201 = {
  data: UserCreateResponse;
  status: 201;
};

export type createUserApiV1UsersPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createUserApiV1UsersPostResponseSuccess =
  createUserApiV1UsersPostResponse201 & {
    headers: Headers;
  };
export type createUserApiV1UsersPostResponseError =
  createUserApiV1UsersPostResponse422 & {
    headers: Headers;
  };

export type createUserApiV1UsersPostResponse =
  | createUserApiV1UsersPostResponseSuccess
  | createUserApiV1UsersPostResponseError;

export const getCreateUserApiV1UsersPostUrl = () => {
  return `/api/v1/users`;
};

export const createUserApiV1UsersPost = async (
  userCreateRequest: UserCreateRequest,
  options?: RequestInit
): Promise<createUserApiV1UsersPostResponse> => {
  return customFetch<createUserApiV1UsersPostResponse>(
    getCreateUserApiV1UsersPostUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(userCreateRequest)
    }
  );
};

/**
 * List all users with pagination (admin only).

Returns:
    UserListResponse with items and total count.

Raises:
    HTTPException: 401 if not authenticated; 403 if not admin.
 * @summary List Users
 */
export type listUsersApiV1UsersGetResponse200 = {
  data: UserListResponse;
  status: 200;
};

export type listUsersApiV1UsersGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type listUsersApiV1UsersGetResponseSuccess =
  listUsersApiV1UsersGetResponse200 & {
    headers: Headers;
  };
export type listUsersApiV1UsersGetResponseError =
  listUsersApiV1UsersGetResponse422 & {
    headers: Headers;
  };

export type listUsersApiV1UsersGetResponse =
  | listUsersApiV1UsersGetResponseSuccess
  | listUsersApiV1UsersGetResponseError;

export const getListUsersApiV1UsersGetUrl = (
  params?: ListUsersApiV1UsersGetParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/users?${stringifiedParams}`
    : `/api/v1/users`;
};

export const listUsersApiV1UsersGet = async (
  params?: ListUsersApiV1UsersGetParams,
  options?: RequestInit
): Promise<listUsersApiV1UsersGetResponse> => {
  return customFetch<listUsersApiV1UsersGetResponse>(
    getListUsersApiV1UsersGetUrl(params),
    {
      ...options,
      method: 'GET'
    }
  );
};

/**
 * Reset the API key for a user (admin only).

Returns:
    ResetKeyResponse with new plaintext API key.

Raises:
    HTTPException: 401 if not authenticated; 403 if not admin; 404 if user not found.
 * @summary Reset Api Key
 */
export type resetApiKeyApiV1UsersUserIdResetKeyPostResponse200 = {
  data: ResetKeyResponse;
  status: 200;
};

export type resetApiKeyApiV1UsersUserIdResetKeyPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type resetApiKeyApiV1UsersUserIdResetKeyPostResponseSuccess =
  resetApiKeyApiV1UsersUserIdResetKeyPostResponse200 & {
    headers: Headers;
  };
export type resetApiKeyApiV1UsersUserIdResetKeyPostResponseError =
  resetApiKeyApiV1UsersUserIdResetKeyPostResponse422 & {
    headers: Headers;
  };

export type resetApiKeyApiV1UsersUserIdResetKeyPostResponse =
  | resetApiKeyApiV1UsersUserIdResetKeyPostResponseSuccess
  | resetApiKeyApiV1UsersUserIdResetKeyPostResponseError;

export const getResetApiKeyApiV1UsersUserIdResetKeyPostUrl = (
  userId: string
) => {
  return `/api/v1/users/${userId}/reset-key`;
};

export const resetApiKeyApiV1UsersUserIdResetKeyPost = async (
  userId: string,
  options?: RequestInit
): Promise<resetApiKeyApiV1UsersUserIdResetKeyPostResponse> => {
  return customFetch<resetApiKeyApiV1UsersUserIdResetKeyPostResponse>(
    getResetApiKeyApiV1UsersUserIdResetKeyPostUrl(userId),
    {
      ...options,
      method: 'POST'
    }
  );
};
